"use client";
import { useEffect, useState } from 'react';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Loader2, ShoppingCart } from 'lucide-react';
import { createClient } from '@/lib/supabase/client';
import { useLanguage } from '@/contexts/LanguageContext';
import { availableVariantOption, defaultVariantOption } from '@/lib/variant-selection';
const localized=(value:any,language:string)=>{try {if(typeof value==='string')value=JSON.parse(value);}catch{}return typeof value==='string'?value:(value?.[language]||value?.ar||value?.en||'');};
export function CartVariantPicker({productId,storeId,onClose,onAdd}:{productId:string;storeId:string;onClose:()=>void;onAdd:(item:any,options:{optionsConfirmed:boolean})=>Promise<boolean>}){
 const {language}=useLanguage(),ar=language==='ar';
 const [data,setData]=useState<any>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[quantity,setQuantity]=useState(1),[selected,setSelected]=useState<Record<string,string>>({});
 useEffect(()=>{let alive=true;const db=createClient();(async()=>{try{
  const [p,v,s]=await Promise.all([db.from('public_products').select('*').eq('id',productId).eq('store_id',storeId).single(),db.from('product_variants').select('*,variant_options(*)').eq('product_id',productId).order('sort_order'),db.from('public_stores').select('currency').eq('id',storeId).single()]);
  if(p.error||v.error||s.error)throw Error(ar?'تعذر تحميل خيارات المنتج. أغلق النافذة وحاول مجددًا.':'Could not load product options. Please retry.');
  if(!alive)return;const defaults:Record<string,string>={};for(const group of v.data||[]){const option=defaultVariantOption<any>(group.variant_options,p.data.ignore_stock);if(option)defaults[group.id]=option.id;}setSelected(defaults);setData({product:p.data,groups:v.data,currency:s.data.currency});
 }catch(e:any){if(alive)setError(e.message);}finally{if(alive)setLoading(false);}})();return()=>{alive=false;};},[productId,storeId,ar]);
 const product=data?.product;let price=Number(product?.sale_price)>0?Number(product.sale_price):Number(product?.price||0);
 const choices=(data?.groups||[]).flatMap((group:any)=>{const option=group.variant_options.find((o:any)=>o.id===selected[group.id]);if(!option)return [];const basePrice=Number(product.sale_price)>0?Number(product.sale_price):Number(product.price);if(option.price!=null)price+=Number(option.price)-basePrice;else price+=Number(option.price_modifier||0);return [{variantId:group.id,variantName:group.name,optionId:option.id,optionLabel:option.label,priceModifier:Number(option.price_modifier||0)}];});
 const missing=(data?.groups||[]).filter((g:any)=>g.required&&!selected[g.id]);
 let max=Number(product?.max_per_order)||100;if(product&&!product.ignore_stock&&product.track_inventory)max=Math.min(max,Number(product.stock_quantity));
 for(const g of data?.groups||[]){const o=g.variant_options.find((o:any)=>o.id===selected[g.id]);if(o&&!product.ignore_stock&&o.manage_stock&&o.stock!=null)max=Math.min(max,Number(o.stock));}
 const money=(amount:number)=>new Intl.NumberFormat(ar?'ar-EG':'en',{style:'currency',currency:data?.currency||'EGP'}).format(amount);
 const add=async()=>{if(missing.length||quantity<1||quantity>max)return;setBusy(true);setError('');try{let images=product.images;if(typeof images==='string')images=JSON.parse(images);const added=await onAdd({productId,productName:product.name,productImage:images?.[0]||null,basePrice:Number(product.price),unitPrice:price,quantity,maxQuantity:max,variants:choices,addedAt:new Date().toISOString()},{optionsConfirmed:true});if(added)onClose();}catch{setError(ar?'تعذرت الإضافة. حاول مرة أخرى.':'Could not add item. Retry.');}finally{setBusy(false);}};
 return <Dialog open onOpenChange={open=>{if(!open&&!busy)onClose();}}><DialogContent dir={ar?'rtl':'ltr'} className="max-w-lg max-h-[90dvh] overflow-y-auto" onClick={e=>e.stopPropagation()}><DialogTitle>{ar?'اختيار خيارات المنتج':'Choose product options'}</DialogTitle><DialogDescription>{ar?'حدد المقاس أو اللون والكمية لإضافة المنتج إلى سلتك.':'Choose options and quantity to add this product to your cart.'}</DialogDescription>
 {loading?<Loader2 className="mx-auto animate-spin"/>:data&&<><h3 className="font-semibold text-lg">{localized(product.name,language)}</h3>{data.groups.map((g:any)=><fieldset key={g.id} className="space-y-3"><legend className="font-medium">{localized(g.name,language)} {g.required&&<span className="text-xs text-muted-foreground">{ar?'(مطلوب)':'(required)'}</span>}</legend><div className="flex flex-wrap gap-2">{g.variant_options.map((o:any)=>{const available=availableVariantOption(o,product.ignore_stock);return <button type="button" key={o.id} disabled={!available||busy} aria-pressed={selected[g.id]===o.id} onClick={()=>setSelected(prev=>({...prev,[g.id]:o.id}))} className={`rounded-lg border px-4 py-3 disabled:opacity-40 ${selected[g.id]===o.id?'border-primary bg-primary/10 ring-1 ring-primary':''}`}>{localized(o.label,language)}{!available&&<span className="block text-xs">{ar?'غير متاح':'Unavailable'}</span>}</button>;})}</div>{g.required&&!selected[g.id]&&<p className="text-sm text-amber-700">{ar?'اختر أحد الخيارات المتاحة':'Choose an available option'}</p>}</fieldset>)}<label className="flex justify-between items-center">{ar?'الكمية':'Quantity'}<input type="number" min={1} max={Math.max(1,max)} value={quantity} onChange={e=>setQuantity(Number(e.target.value))} className="w-24 border rounded-lg p-2"/></label><div className="flex justify-between font-bold border-t pt-4"><span>{ar?'الإجمالي':'Total'}</span><span>{money(price*quantity)}</span></div>{quantity>max&&<p role="alert" className="text-red-600">{ar?`الكمية المتاحة لهذه الاختيارات: ${Math.max(0,max)}`:`Available quantity: ${Math.max(0,max)}`}</p>}<Button className="w-full h-12" disabled={busy||missing.length>0||quantity<1||!Number.isInteger(quantity)||quantity>max} onClick={add}>{busy?<Loader2 className="animate-spin"/>:<ShoppingCart className="w-4 h-4 mx-2"/>}{ar?'إضافة للسلة':'Add to cart'}</Button></>}{error&&<p role="alert" className="text-red-600">{error}</p>}
 </DialogContent></Dialog>;
}
