"use client";
import {useEffect,useState} from 'react';
import {createClient} from '@/lib/supabase/client';
import {QuickOrderForm} from './QuickOrderForm';
import {availableVariantOption,defaultVariantOption,variantUnitPrice} from '@/lib/variant-selection';
export function InlineProductCheckout({productId,storeSlug,language}:{productId:string;storeSlug:string;language:string}){
 const [data,setData]=useState<any>(null),[choices,setChoices]=useState<Record<string,string>>({}),[quantity,setQuantity]=useState(1),[error,setError]=useState('');const ar=language==='ar';
 useEffect(()=>{let alive=true;(async()=>{try{const db=createClient();const [p,s,v]=await Promise.all([db.from('public_products').select('*').eq('id',productId).single(),db.from('public_stores').select('id,slug,currency,settings').eq('slug',storeSlug).single(),db.from('product_variants').select('*,variant_options(*)').eq('product_id',productId).order('sort_order')]);if(p.error||s.error||v.error||p.data.store_id!==s.data.id)throw Error();if(!alive)return;const defaults:Record<string,string>={};for(const group of v.data){const option=defaultVariantOption<any>(group.variant_options,p.data.ignore_stock);if(option)defaults[group.id]=option.id;}setChoices(defaults);setData({product:p.data,store:s.data,variants:v.data});}catch{if(alive)setError(ar?'تعذر تحميل نموذج الطلب. حدّث الصفحة للمحاولة مجددًا.':'Could not load checkout. Refresh to retry.');}})();return()=>{alive=false;};},[productId,storeSlug,ar]);
 if(!data)return <section id="landing-inline-order" className="max-w-xl mx-auto my-8 p-5" role="status">{error||(ar?'جارٍ تجهيز نموذج الطلب…':'Loading checkout…')}</section>;
 const selected=data.variants.flatMap((g:any)=>g.variant_options.filter((o:any)=>o.id===choices[g.id]));const base=Number(data.product.sale_price)>0?Number(data.product.sale_price):Number(data.product.price);const subtotal=variantUnitPrice(base,selected)*quantity;
 return <div id="landing-inline-order" dir={ar?'rtl':'ltr'} className="max-w-xl mx-auto my-8 space-y-4 px-4"><section className="rounded-2xl border p-5 space-y-4 bg-background"><h2 className="font-bold text-xl">{ar?'أكمل طلبك هنا':'Complete your order here'}</h2>{data.variants.map((g:any)=><label key={g.id} className="block space-y-2"><span>{g.name?.[language]||g.name?.ar} {g.required?'*':''}</span><select className="border rounded-lg p-3 w-full" value={choices[g.id]||''} onChange={e=>setChoices(c=>({...c,[g.id]:e.target.value}))}><option value="">{ar?'اختر':'Choose'}</option>{g.variant_options.map((o:any)=><option key={o.id} value={o.id} disabled={!availableVariantOption(o,data.product.ignore_stock)}>{o.label?.[language]||o.label?.ar}</option>)}</select></label>)}<label className="flex justify-between items-center">{ar?'الكمية':'Quantity'}<input className="w-24 p-2 rounded-lg border" type="number" min={1} max={100} value={quantity} onChange={e=>setQuantity(Math.max(1,Math.min(100,Math.floor(Number(e.target.value)||1))))}/></label></section><QuickOrderForm inline isOpen onClose={()=>{}} product={data.product} quantity={quantity} subtotal={subtotal} variants={data.variants} selections={Object.fromEntries(Array.from({length:quantity},(_,i)=>[i,choices]))} store={data.store}/></div>;
}
