"use client";
import { useEffect,useState } from 'react';
import { createClient } from '@/lib/supabase/client';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { normalizePhone } from '@/lib/checkout-validation';
export default function VerifyPage(){
 const db=createClient();const [status,setStatus]=useState<any>(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[code,setCode]=useState(''),[challenge,setChallenge]=useState(''),[cooldown,setCooldown]=useState(0);
 const headers=async()=>{const {data:{session}}=await db.auth.getSession();return {'Content-Type':'application/json',Authorization:`Bearer ${session?.access_token||''}`};};
 const load=async()=>{const response=await fetch('/api/auth/verification-status',{headers:await headers(),cache:'no-store'});if(response.status===401){window.location.assign('/login');return;}const data=await response.json();if(!response.ok){setError(data.error);return;}setStatus(data);};
 useEffect(()=>{load().catch(()=>setError('تعذر الاتصال؛ حدّث الصفحة وحاول مجددًا.'));},[]);
 useEffect(()=>{if(cooldown<=0)return;const timer=setTimeout(()=>setCooldown(c=>Math.max(0,c-1)),1000);return()=>clearTimeout(timer);},[cooldown]);
 const send=async(method:string)=>{setBusy(true);setError('');setMessage('');try{const response=await fetch('/api/auth/send-otp',{method:'POST',headers:await headers(),body:JSON.stringify({method})});const data=await response.json();if(!response.ok)throw Error(data.error);setChallenge(data.challengeId);setCode('');setCooldown(data.retryAfter);setMessage('أُرسل الرمز. أدخله خلال 10 دقائق، وراجع البريد غير المرغوب فيه إن لم تجده.');}catch(e:any){setError(e.message);}finally{setBusy(false);}};
 const verify=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setError('');try{const response=await fetch('/api/auth/verify-otp',{method:'POST',headers:await headers(),body:JSON.stringify({challengeId:challenge,code:normalizePhone(code)})});const data=await response.json();if(!response.ok)throw Error(data.error);setMessage('تم تفعيل حسابك بنجاح.');setChallenge('');await load();}catch(e:any){setError(e.message);}finally{setBusy(false);}};
 return <main dir="rtl" className="min-h-screen bg-slate-50 px-4 py-14"><section className="mx-auto max-w-lg rounded-2xl border bg-white p-7 shadow-sm space-y-6"><span className={`inline-block rounded-full px-3 py-1 text-sm ${status?.verified?'bg-green-100 text-green-800':'bg-amber-100 text-amber-900'}`}>{status?.verified?'حساب مفعّل':'الحساب يحتاج إلى التفعيل'}</span><h1 className="text-2xl font-bold">تفعيل حساب التاجر</h1><p className="text-slate-600">أكد بريدك الإلكتروني أو رقمك عبر واتساب. يكفي تأكيد وسيلة واحدة لاستخدام لوحة المتجر.</p>
 {status?<><div className="rounded-lg border p-4 space-y-2"><p>البريد: <span dir="ltr">{status.email}</span></p><p className="text-sm">{status.emailVerified?'البريد موثّق ✓':'البريد غير موثّق'}</p>{!status.emailVerified&&<Button className="w-full" disabled={busy||cooldown>0||!status.emailAvailable} onClick={()=>send('email')}>{cooldown>0?`إعادة الإرسال بعد ${cooldown} ثانية`:'إرسال رمز إلى البريد'}</Button>}{!status.emailAvailable&&<p className="text-sm text-red-600">خدمة البريد غير متاحة مؤقتًا. تواصل مع الدعم.</p>}</div><div className="rounded-lg border p-4 space-y-2"><p>واتساب: <span dir="ltr">{status.phone||'لا يوجد رقم مسجل'}</span></p><p className="text-sm">{status.phoneVerified?'الرقم موثّق ✓':'الرقم غير موثّق'}</p>{!status.phoneVerified&&<Button variant="outline" className="w-full" disabled={busy||cooldown>0||!status.whatsappAvailable||!status.phone} onClick={()=>send('whatsapp')}>إرسال رمز عبر واتساب</Button>}{!status.whatsappAvailable&&<p className="text-sm text-slate-500">تفعيل واتساب غير متاح مؤقتًا. يمكنك إكمال التفعيل بالبريد الآن.</p>}</div></>:<p>جارٍ تحميل بيانات الحساب…</p>}
 {challenge&&<form className="space-y-3" onSubmit={verify}><label htmlFor="activation-code">رمز التفعيل</label><Input id="activation-code" inputMode="numeric" autoComplete="one-time-code" maxLength={6} dir="ltr" value={code} onChange={e=>setCode(normalizePhone(e.target.value))} placeholder="000000" required/><Button className="w-full" disabled={busy||code.length!==6}>تأكيد الرمز وتفعيل الحساب</Button></form>}
 {error&&<p role="alert" className="rounded-lg bg-red-50 p-3 text-red-700">{error}</p>}{message&&<p role="status" className="rounded-lg bg-green-50 p-3 text-green-800">{message}</p>}
 {status?.verified&&<Button className="w-full" onClick={()=>window.location.assign('/dashboard')}>متابعة إلى لوحة التحكم</Button>}
 <div className="flex justify-between text-sm"><a href="/" className="underline">الرئيسية والتواصل مع الدعم</a><button onClick={async()=>{await db.auth.signOut();window.location.assign('/login');}} className="underline">تسجيل الخروج</button></div>
 </section></main>;
}
