'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {Check} from 'lucide-react';
import {savePlanIntent} from '@/lib/plan-intent';
import {createClient} from '@/lib/supabase/client';
import {useLanguage} from '@/contexts/LanguageContext';
import styles from './marketing.module.css';
type Plan={id:string;slug:string;name_ar:string;name_en:string;description_ar?:string;description_en?:string;price_monthly:number;features?:Record<string,unknown>};
type Feature={id:string;name_ar:string;name_en:string;type:string};
type Value={plan_id:string;feature_id:string;value:string};
export function LivePricing(){
 const {language}=useLanguage();const ar=language==='ar';const tr=(a:string,e:string)=>ar?a:e;
 const [plans,setPlans]=useState<Plan[]>([]),[features,setFeatures]=useState<Feature[]>([]),[values,setValues]=useState<Value[]>([]),[state,setState]=useState<'loading'|'ready'|'error'>('loading'),[attempt,setAttempt]=useState(0);
 useEffect(()=>{let active=true;setState('loading');const db=createClient();Promise.all([db.from('plans').select('id,slug,name_ar,name_en,description_ar,description_en,price_monthly,features').eq('is_active',true).order('price_monthly'),db.from('plan_features').select('id,name_ar,name_en,type').order('group').order('id'),db.from('plan_feature_values').select('plan_id,feature_id,value')]).then(([p,f,v])=>{if(!active)return;if(p.error||f.error||v.error||!p.data?.length){setState('error');return}setPlans(p.data);setFeatures(f.data||[]);setValues(v.data||[]);setState('ready')}).catch(()=>{if(active)setState('error')});return()=>{active=false}},[attempt]);
 const featureValue=(plan:Plan,feature:Feature)=>{const raw=values.find(v=>v.plan_id===plan.id&&v.feature_id===feature.id)?.value??plan.features?.[feature.id];const v=String(raw??'');const available=feature.type==='boolean'?v==='true':feature.type==='integer'?(Number(v)>0||v==='-1'):!!v&&v!=='none'&&v!=='false';const text=feature.type==='boolean'?'':v==='-1'?tr('غير محدود','Unlimited'):v;return {available,text}};
 const choose=(p:Plan)=>savePlanIntent(p.id);
 return <section id="pricing" className={styles.pricing} aria-labelledby="pricing-title"><div className={styles.sectionHeading}><span className={styles.eyebrow}>{tr('باقات تناسب خطواتك','PLANS FOR YOUR NEXT STEP')}</span><h2 id="pricing-title">{tr('اختر ما يحتاجه متجرك الآن.','Choose what your store needs now.')}</h2><p>{tr('الأسعار التالية للاشتراك الشهري بالدولار، وتُحمّل من الباقات المفعّلة. قد تُضاف عمولات الطلبات والخدمات الاختيارية.','Monthly subscriptions in USD, loaded from active plans. Order commissions and optional add-ons may be charged separately.')}</p></div>
 {state==='loading'&&<p role="status" className={styles.planError}>{tr('جاري تحميل الباقات الحالية…','Loading current plans…')}</p>}
 {state==='error'&&<div role="alert" className={styles.planError}><p>{tr('تعذّر تحميل الأسعار الحالية. لن نعرض أسعارًا قديمة أو تقديرية.','Current prices could not be loaded. We will not show stale or estimated prices.')}</p><button className={styles.textButton} onClick={()=>setAttempt(v=>v+1)}>{tr('إعادة المحاولة','Try again')}</button> · <Link href="/contact">{tr('تواصل مع الدعم','Contact support')}</Link></div>}
 {state==='ready'&&<><div className={styles.plans}>{plans.map(p=>{const included=features.filter(f=>featureValue(p,f).available);return <article className={styles.plan} key={p.id} data-plan-id={p.id}><span className={styles.planBadge}>{Number(p.price_monthly)===0?tr('لبداية متجرك','Start your store'):tr('اشتراك شهري','Monthly subscription')}</span><h3>{ar?p.name_ar:p.name_en}</h3><p className={styles.planDescription}>{(ar?p.description_ar:p.description_en)||tr('اختر بناءً على المزايا وحدود الاستخدام الموضحة.','Choose according to the features and limits below.')}</p><div className={styles.price}><bdi>{Number(p.price_monthly)===0?tr('مجاني','Free'):new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(Number(p.price_monthly))}</bdi><small>{tr('اشتراك شهري · USD','Monthly subscription · USD')}</small></div><ul>{included.length?included.map(f=>{const v=featureValue(p,f);return <li key={f.id}><Check size={16}/><span>{ar?f.name_ar:f.name_en}{v.text&&<>: <bdi>{v.text}</bdi></>}</span></li>}):<li>{tr('راجع تفاصيل الباقة مع الدعم.','Contact support for plan details.')}</li>}</ul><Link className={styles.primary} href={`/signup?plan=${encodeURIComponent(p.id)}&cycle=monthly`} onClick={()=>choose(p)} data-marketing-event="plan_select">{Number(p.price_monthly)===0?tr('ابدأ بهذه الباقة','Start with this plan'):tr('اختر هذه الباقة','Choose this plan')}</Link><small>{tr('لا يتم الخصم عند الضغط. نحتفظ باختيارك لإتمامه بعد التسجيل.','No charge on click. Your choice is saved for after signup.')}</small></article>})}</div><details className={styles.planComparison}><summary className={styles.textButton}>{tr('مقارنة جميع المزايا والحدود','Compare all features and limits')}</summary><table><caption className="sr-only">{tr('مقارنة الباقات الحالية','Current plan comparison')}</caption><thead><tr><th scope="col">{tr('الميزة','Feature')}</th>{plans.map(p=><th scope="col" key={p.id}>{ar?p.name_ar:p.name_en}</th>)}</tr></thead><tbody>{features.map(f=><tr key={f.id}><th scope="row">{ar?f.name_ar:f.name_en}</th>{plans.map(p=>{const v=featureValue(p,f);return <td key={p.id}>{v.available?(v.text||tr('مضمنة','Included')):tr('غير مضمنة','Not included')}</td>})}</tr>)}</tbody></table></details></>}
 <div className={styles.costNote}><strong>{tr('احسب التكلفة الكاملة قبل التفعيل','Understand the full cost before activation')}</strong><p>{tr('الاشتراك + عمولة الطلبات حسب إعدادات متجرك + الإضافات التي تختارها. قد توجد رسوم منفصلة لدى مزودي الدفع والشحن. راجع تفاصيل العمولة والخدمات في لوحة متجرك قبل تأكيد أي عملية.','Subscription + order commissions according to your store settings + add-ons you choose. Providers may have separate fees. Review commission and service details in your dashboard before confirming a transaction.')}</p><p>{tr('عملة منتجات متجرك مستقلة عن محفظة المنصة بالدولار. شحن المحافظ المحلية بالجنيه المصري مع عرض سعر الصرف والمبلغ المحوّل قبل التأكيد. الاشتراكات المعروضة شهرية.','Store product currency is separate from the platform USD wallet. Local wallet top-ups use EGP and show the exchange rate and converted amount before confirmation. Listed subscriptions are monthly.')}</p><Link href="/terms">{tr('شروط الاستخدام والإلغاء والاسترداد','Usage, cancellation and refund terms')}</Link></div>
 </section>
}
