'use client';

import Link from 'next/link';
import { useRef, useState } from 'react';
import { ArrowUpLeft, Check, ChevronDown, Play, ShoppingBag, SlidersHorizontal, Package, BarChart3, ShieldCheck, ArrowRight } from 'lucide-react';
import { useLanguage } from '@/contexts/LanguageContext';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { LivePricing } from './LivePricing';
import styles from './marketing.module.css';

export function MarketingHome() {
 const {language}=useLanguage();const ar=language==='ar';const tr=(a:string,e:string)=>ar?a:e;
 const videoButton=useRef<HTMLButtonElement>(null);
 const [video,setVideo]=useState(false);const [videoError,setVideoError]=useState(false);const [walkthrough,setWalkthrough]=useState(0);
 const steps=[tr('أنشئ هوية متجرك','Make it yours'),tr('أضف المنتج وخياراته','Add products and options'),tr('اختر تجربة الطلب','Choose the buying experience'),tr('تابع الطلبات من مكان واحد','Keep orders in one place')];
 const faqs=[
 [tr('هل أحتاج خبرة برمجية؟','Do I need to code?'),tr('لا. يمكنك إعداد المتجر وإضافة المنتجات وتعديل الثيم من لوحة التحكم. جرّب المعاينة أولًا لتتعرف على تجربة المنتج والخيارات والسلة.','No. Set up your store, add products and customize its theme from the dashboard. Try the preview to explore products, options and cart.')],
 [tr('ما الذي أدفعه غير الاشتراك؟','What do I pay beyond the subscription?'),tr('سعر الباقة لا يعني إلغاء عمولات الطلبات أو رسوم الخدمات الإضافية. راجع عمولة متجرك ورصيد المحفظة وسعر كل إضافة في لوحة التحكم قبل تفعيلها. رسوم مزودي الدفع والشحن، عند ربطهم، منفصلة.','A subscription does not waive order commissions or add-on fees. Review your store commission, wallet balance and each add-on price before activation. External payment and shipping provider fees are separate.')],
 [tr('كيف تعمل العملات وشحن المحفظة؟','How do currencies and wallet top-ups work?'),tr('يمكنك اختيار عملة أسعار متجرك. رصيد محفظة المنصة بالدولار، والمحافظ المحلية الحالية تستقبل الجنيه المصري؛ تظهر قيمة التحويل وسعر الصرف في مسار الشحن قبل التأكيد.','Choose the currency for your store prices. The platform wallet is in USD; current local receiving wallets accept EGP. The top-up flow shows the converted amount and exchange rate before confirmation.')],
 [tr('هل النطاق المخصص وصفحات الهبوط ضمن كل باقة؟','Are custom domains and landing pages in every plan?'),tr('يعتمد ذلك على الباقة والخدمات المفعلة. المقارنة أدناه تعرض إعدادات الباقات الحالية؛ الخدمات الإضافية تُفعّل بشكل منفصل عند عدم تضمينها.','This depends on your plan and active add-ons. The comparison shows current plan settings. Services not included may require a separate add-on.')],
 [tr('هل الدفع والشحن وواتساب تعمل تلقائيًا؟','Are payments, shipping and WhatsApp connected automatically?'),tr('لا تفترض أن حساب مزود خارجي يُنشأ بمجرد التسجيل. راجع طرق الدفع والشحن المتاحة في إعدادات متجرك ومتطلبات كل ربط. تفعيل واتساب يحتاج مزودًا وإعدادًا منفصلًا؛ لا نعد بربط جاهز دون ذلك.','Signing up does not create an external provider account. Review available payment and shipping methods and their setup requirements. WhatsApp activation requires a provider and separate configuration.')],
 [tr('ماذا يحدث بعد إنشاء الحساب؟','What happens after signup?'),tr('تدخل بياناتك ورقم هاتفك وبيانات المتجر، ثم تؤكد بريدك قبل استخدام وظائف التاجر المحمية. بعد ذلك أضف أول منتج وراجع تجربة الطلب قبل مشاركة رابط المتجر.','Enter your contact and store details, then verify your email before using protected merchant features. Add your first product and check the buying experience before sharing your store.')],
 [tr('كيف أتواصل أو أطلب إلغاء الاشتراك؟','How do I contact support or request cancellation?'),tr('استخدم صفحة التواصل أو زر الدعم، واذكر اسم المتجر والخدمة المطلوبة. اطلب توضيح شروط الإلغاء والاسترداد قبل الشراء؛ لا نعرض وعدًا باسترداد أو وقت استجابة غير معتمد.','Use the contact page or support button and include your store and the service concerned. Confirm cancellation and refund terms before purchase; we do not promise an unapproved refund or response time.')],
 ];
 return <div className={styles.marketing} dir={ar?'rtl':'ltr'}>
  <a className={styles.skip} href="#main-content">{tr('تخطي إلى المحتوى','Skip to content')}</a>
  <main id="main-content">
   <section className={styles.hero}>
    <div className={styles.heroCopy}><span className={styles.eyebrow}><span/> {tr('مساحة واحدة لتجارتك','ONE SPACE FOR YOUR BUSINESS')}</span>
     <h1>{tr('متجرك. منتجاتك.','Your store. Your products.')}<br/><em>{tr('وطلباتك تحت السيطرة.','Your orders, in order.')}</em></h1>
     <p>{tr('أنشئ متجرك وصفحات بيعك، واعرض المنتجات بخياراتها، وتابع الطلبات من لوحة عربية واضحة. ابدأ بخطوة بسيطة، وطوّر متجرك على مهل.','Build your store and selling pages, offer product options, and manage orders from one clear dashboard. Start simple and grow at your pace.')}</p>
     <div className={styles.actions}><Link href="/signup" className={styles.primary} data-marketing-event="signup_click">{tr('أنشئ متجرك مجانًا','Create your free store')}<ArrowUpLeft size={19}/></Link><Link href="/demo" className={styles.secondary} data-marketing-event="demo_click">{tr('جرّب متجرًا جاهزًا','Try a demo store')}<ArrowRight size={18}/></Link></div>
     <div className={styles.assurances}><span><Check size={15}/>{tr('بلا برمجة','No coding')}</span><span><Check size={15}/>{tr('لا بطاقة لإنشاء الحساب','No card to sign up')}</span><span><Check size={15}/>{tr('الأسعار والحدود موضحة أدناه','Plan limits below')}</span></div>
    </div>
    <div className={styles.heroVisual}><div className={styles.browserBar}><span>orderly / studio</span><span>● ● ●</span></div><div className={styles.previewLabel}>{tr('معاينة توضيحية • بيانات تجريبية','Illustrative preview • sample data')}</div><div className={styles.previewHeading}><span>{tr('يوم جديد. طلبات مرتبة.','A fresh day. Orders in order.')}</span><ShoppingBag size={25}/></div><div className={styles.previewGrid}><div className={styles.sampleProduct}><div className={styles.productArt}><ShoppingBag size={85} strokeWidth={1}/></div><small>EVERYDAY COLLECTION</small><strong>{tr('حقيبة كل يوم','Everyday tote')}</strong><span dir="ltr">EGP 450</span><div className={styles.swatches}><i/><i/><i/></div></div><div className={styles.orderPreview}>{[tr('اختيار اللون والمقاس','Choose color and size'),tr('إضافة إلى السلة','Add to cart'),tr('بيانات طلب واضحة','Clear order details')].map((v,i)=><div key={v}><span>0{i+1}</span><strong>{v}</strong><Check size={16}/></div>)}<Link href="/demo">{tr('افتح التجربة التفاعلية','Open the interactive demo')} ↗</Link></div></div><div className={styles.previewFoot}><ShieldCheck size={16}/>{tr('التجربة لا تُنشئ طلبات حقيقية','The demo does not place real orders')}</div></div>
   </section>
   <div className={styles.factStrip}>{[tr('واجهة عربية وإنجليزية','Arabic & English'),tr('خيارات متعددة للمنتج','Product variants'),tr('سلة أو طلب مباشر','Cart or direct order'),tr('متابعة الطلبات غير المكتملة','Incomplete checkout tracking')].map(x=><span key={x}><Check size={17}/>{x}</span>)}</div>
   <section id="features" className={styles.section}><div className={styles.sectionHeading}><span className={styles.eyebrow}>{tr('من أول منتج إلى آخر طلب','FROM PRODUCT TO ORDER')}</span><h2>{tr('أقل تشتتًا. أكثر وضوحًا.','Less switching. More clarity.')}</h2><p>{tr('أدوات عملية لكل خطوة من رحلة البيع. توافر بعض الخدمات يتوقف على باقتك والإضافات المفعلة.','Practical tools for each step of selling. Some services depend on your plan and active add-ons.')}</p></div><div className={styles.featureGrid}>{[
 [ShoppingBag,tr('متجر يعكس علامتك','A store that feels like you'),tr('رتّب التصنيفات، وأضف الصور وخيارات المنتجات، واختر تصميمًا يناسب ما تبيعه.','Organize categories, add images and product options, and choose a design that suits your brand.')],
 [SlidersHorizontal,tr('تجربة شراء تناسب المنتج','The right buying experience'),tr('استخدم السلة للمشتريات المتعددة، أو الطلب المباشر داخل صفحة المنتج للحملات المركزة.','Use a cart for multiple products or an inline order form for focused product campaigns.')],
 [BarChart3,tr('رؤية أوضح للطلبات','A clearer view of orders'),tr('تابع الطلبات وحالاتها والطلبات غير المكتملة، وحدد أين يحتاج العميل إلى المساعدة.','Review orders, statuses and incomplete checkouts to see where customers may need help.')]
 ].map(([Icon,title,desc])=>{const I=Icon as typeof ShoppingBag;return <article key={String(title)}><I size={26}/><h3>{String(title)}</h3><p>{String(desc)}</p></article>})}</div></section>
   <section id="demo" className={`${styles.section} ${styles.gallerySection}`}><div className={styles.sectionHeading}><span className={styles.eyebrow}>{tr('شاهد قبل أن تسجل','EXPLORE BEFORE SIGNUP')}</span><h2>{tr('ثلاث تجارب. نفس سهولة الطلب.','Three looks. One easy checkout.')}</h2><p>{tr('نماذج توضيحية لتجربة المنتجات والخيارات والسلة والطلب المباشر، وليست متاجر عملاء أو وعودًا بإتاحة ثيم ضمن كل باقة.','Illustrative demos of product options, cart and direct checkout. These are not customer stores or a promise that a theme is included in every plan.')}</p></div><div className={styles.gallery}>{[['everyday','EVERYDAY',tr('منتجات يومية','Everyday goods'),'#e4eee7'],['beauty','BOTANICAL',tr('العناية والجمال','Beauty & care'),'#efe3dc'],['studio','STUDIO',tr('صفحة منتج مركزة','Focused product page'),'#dfe5f3']].map(([slug,name,label,color])=><Link href={`/demo?theme=${slug}`} key={slug} className={styles.galleryCard} data-marketing-event="theme_preview"><div style={{background:color}}><span>{name}</span><ShoppingBag size={80} strokeWidth={1}/><small>{tr('منتجات توضيحية','Sample products')}</small></div><h3>{label}<ArrowUpLeft size={20}/></h3><p>{tr('افتح المعاينة التفاعلية','Open interactive preview')}</p></Link>)}</div></section>
   <section id="how-it-works" className={styles.section}><div className={styles.walkthrough}><div><span className={styles.eyebrow}>{tr('تعرف عليها في دقيقة','A ONE-MINUTE WALKTHROUGH')}</span><h2>{tr('خطوتك التالية واضحة.','Your next step is clear.')}</h2><p>{tr('جولة قصيرة مكتوبة، يمكنك التحكم في سرعتها. التسجيل يبدأ ببياناتك وتأكيد بريدك، ثم إعداد متجرك.','A short, text-first tour at your own pace. Start with signup and email verification, then set up your store.')}</p><button ref={videoButton} type="button" className={styles.textButton} onClick={()=>{setVideoError(false);setVideo(true)}}><Play size={17}/>{tr('جولة مرئية · 60 ثانية','Visual walkthrough · 60 seconds')}</button></div><div className={styles.steps}>{steps.map((title,i)=><button type="button" key={title} aria-expanded={walkthrough===i} onClick={()=>setWalkthrough(i)}><span>0{i+1}</span><div><strong>{title}</strong>{walkthrough===i&&<p>{[
 tr('سمِّ متجرك، وارفع شعارك، وحدد عملة عرض الأسعار.','Name your store, upload your logo and choose your display currency.'),tr('أضف صورًا وسعرًا وخيارات مثل اللون والمقاس؛ كل خيار واضح للعميل.','Add images, a price and options such as color and size, clearly shown to customers.'),tr('اختر السلة أو الطلب المباشر، وراجع الحقول قبل مشاركة رابطك.','Choose cart or direct checkout and review the fields before sharing your link.'),tr('راجع الطلبات وحالاتها من لوحة التحكم، وتابع ما لم يُكتمل.','Review orders and their statuses from the dashboard, including incomplete checkouts.')][i]}</p>}</div><ChevronDown size={18}/></button>)}</div></div></section>
   <section className={`${styles.section} ${styles.integrations}`}><div><span className={styles.eyebrow}>{tr('روابط واضحة، بلا وعود مبهمة','CLEAR CONNECTIONS, CLEAR REQUIREMENTS')}</span><h2>{tr('اعرف ما تحتاجه قبل الربط.','Know what a connection needs.')}</h2></div><div className={styles.integrationGrid}><article><strong>Google Sheets</strong><p>{tr('يحتاج مشاركة الملف مع بريد الربط وإدخال إعدادات الجدول من لوحة المتجر.','Requires sharing the sheet with the integration email and configuring it in your store.')}</p></article><article><strong>{tr('الدومين وصفحات الهبوط','Domains & landing pages')}</strong><p>{tr('حسب الباقة أو الإضافة المفعلة. الدومين المخصص يحتاج ضبط DNS.','Available by plan or add-on. Custom domains require DNS configuration.')}</p></article><article><strong>{tr('الدفع والشحن وواتساب','Payments, shipping & WhatsApp')}</strong><p>{tr('راجع الطرق المتاحة ومتطلبات المزود. لا تُنشأ حسابات مزودين خارجيين تلقائيًا عند التسجيل.','Review available methods and provider requirements. External provider accounts are not created automatically.')}</p></article></div></section>
   <LivePricing/>
   <section id="faq" className={`${styles.section} ${styles.faq}`}><div className={styles.sectionHeading}><span className={styles.eyebrow}>{tr('قبل أن تبدأ','BEFORE YOU START')}</span><h2>{tr('أسئلة تستحق إجابات واضحة.','Good questions. Clear answers.')}</h2></div>{faqs.map(([q,a])=><details key={q}><summary>{q}<ChevronDown size={18}/></summary><p>{a}</p></details>)}</section>
   <section className={styles.finalCta}><span className={styles.eyebrow}>{tr('ابدأ بما لديك','START WHERE YOU ARE')}</span><h2>{tr('منتجك القادم يستحق متجرًا مرتبًا.','Your next product deserves a great store.')}</h2><p>{tr('جرّب الواجهة، راجع التكاليف، ثم ابدأ عندما تكون مستعدًا.','Explore the experience, review the costs, then start when you are ready.')}</p><Link href="/signup" className={styles.primary} data-marketing-event="signup_click">{tr('أنشئ متجرك مجانًا','Create your free store')}<ArrowUpLeft size={18}/></Link></section>
  </main>
  <Dialog open={video} onOpenChange={setVideo}><DialogContent preventCloseOutside={false} onCloseAutoFocus={e=>{e.preventDefault();videoButton.current?.focus()}} className="max-w-4xl"><DialogHeader><DialogTitle>{tr('جولة داخل أوردرلي','An Orderly walkthrough')}</DialogTitle><DialogDescription>{tr('جولة صامتة من التجربة التوضيحية، بنص عربي وإنجليزي. الجولة المكتوبة متاحة في الصفحة.','A silent demo walkthrough with Arabic and English text. The written tour is also available on this page.')}</DialogDescription></DialogHeader>{video&&<video src="/videos/quick-tour.mp4" poster="/videos/quick-tour-poster.png" controls playsInline preload="none" aria-label={tr('فيديو شرح المنصة','Platform walkthrough video')} onError={()=>setVideoError(true)} className="w-full rounded-xl"><track kind="captions" src="/videos/quick-tour-ar.vtt" srcLang="ar" label="العربية" default={ar}/><track kind="captions" src="/videos/quick-tour-en.vtt" srcLang="en" label="English" default={!ar}/></video>}{videoError&&<p role="alert">{tr('تعذّر تشغيل الفيديو. يمكنك متابعة الجولة المكتوبة أو تجربة المتجر.','The video could not load. Use the written tour or try the demo store.')}</p>}<Link href="/demo">{tr('افتح المتجر التجريبي','Open demo store')}</Link></DialogContent></Dialog>
 </div>;
}
