export const LANDING_PRESETS = {
  modern: {
    name: "نقاء",
    en: "Pure",
    accent: "#234d42",
    background: "#f5f4ef",
    ink: "#172c25",
    mood: "editorial",
  },
  elegant: {
    name: "أناقة",
    en: "Atelier",
    accent: "#9c583b",
    background: "#faf3eb",
    ink: "#38271e",
    mood: "editorial",
  },
  noir: {
    name: "ليلي",
    en: "Noir",
    accent: "#d7b881",
    background: "#17191b",
    ink: "#f5eee2",
    mood: "dark",
  },
  cyber: {
    name: "تقني",
    en: "Circuit",
    accent: "#6c5ce7",
    background: "#f1f0fc",
    ink: "#212038",
    mood: "technical",
  },
  hype: {
    name: "جريء",
    en: "Bold",
    accent: "#d34d32",
    background: "#fff7ed",
    ink: "#33201b",
    mood: "bold",
  },
  trust: {
    name: "هادئ",
    en: "Calm",
    accent: "#246a86",
    background: "#eff6f8",
    ink: "#193744",
    mood: "soft",
  },
  flash: {
    name: "حيوي",
    en: "Pop",
    accent: "#7251a1",
    background: "#f8f0fa",
    ink: "#3c2549",
    mood: "bold",
  },
} as const;
export type StudioTemplate = keyof typeof LANDING_PRESETS;
export const LANDING_SECTIONS = [
  "benefits",
  "story",
  "gallery",
  "faq",
  "testimonials",
  "guarantee",
];
export const sectionNames: Record<string, string> = {
  benefits: "المميزات",
  story: "تفاصيل المنتج",
  gallery: "معرض الصور",
  faq: "الأسئلة الشائعة",
  testimonials: "آراء العملاء",
  guarantee: "سياسة المتجر",
};
export const newLandingContent = () => ({
  design_version: 2,
  headline: { ar: "", en: "" },
  subheadline: { ar: "", en: "" },
  cta_text: { ar: "اطلب الآن", en: "Order now" },
  eyebrow: { ar: "", en: "" },
  brand_name: "",
  hero_image: "",
  accent_color: "#234d42",
  bg_color: "#f5f4ef",
  benefits: [],
  product_sections: [],
  gallery: [],
  faq: [],
  testimonials: [],
  guarantee_text: { ar: "", en: "" },
  sections_order: [...LANDING_SECTIONS],
  hidden_sections: [],
  image_fit: "contain",
  sticky_cta: true,
});
