'use client';
import {useState} from 'react';
import {appendVariantOptions, VariantEditorGroup} from '@/lib/variant-editor';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';

export function QuickVariantEditor({groups,onChange,ar,basePrice,onUpload}:{groups:VariantEditorGroup[];onChange:(groups:VariantEditorGroup[])=>void;ar:boolean;basePrice?:string|number;onUpload:(g:number,o:number,e:React.ChangeEvent<HTMLInputElement>)=>void}) {
 const [texts,setTexts]=useState<Record<number,string>>({});const [bulk,setBulk]=useState<Record<number,{price:string;stock:string}>>({});
 const t=(a:string,e:string)=>ar?a:e;
 const update=(i:number,patch:Partial<VariantEditorGroup>)=>onChange(groups.map((g,j)=>j===i?{...g,...patch}:g));
 const option=(i:number,j:number,patch:any)=>update(i,{options:groups[i].options.map((o,k)=>k===j?{...o,...patch}:o)});
 const create=(kind:string)=>{const names:Record<string,string[]>={size:['المقاس','Size'],color:['اللون','Color'],capacity:['السعة','Capacity'],custom:['','']};onChange([...groups,{name:{ar:names[kind][0],en:names[kind][1]},display_type:kind==='color'?'color':'buttons',option_type:kind==='color'?'color':'text',required:true,sort_order:groups.length,options:[]}])};
 return <div className="space-y-5">
  <div className="rounded-xl bg-teal-50 p-4 text-sm text-teal-950"><strong>{t('أضف خيارات المنتج في خطوة واحدة','Add product options in one step')}</strong><p className="mt-1">{t('اختر نوع المجموعة، اكتب القيم مفصولة بفاصلة، ثم عدّل ما يختلف فقط. السعر الفارغ يتبع سعر المنتج.','Choose a group, enter comma-separated values, then edit only what differs. An empty price follows the product price.')}</p><p className="mt-1 text-xs">{t('المجموعات مستقلة كما كانت؛ لا يتم إنشاء تركيبات أو تغيير طريقة جمع الأسعار تلقائيًا.','Groups remain independent; no combinations or price rules are changed automatically.')}</p></div>
  <div className="flex flex-wrap gap-2">{[['size','مقاسات','Sizes'],['color','ألوان','Colors'],['capacity','سعات / أحجام','Capacity'],['custom','مجموعة أخرى','Custom group']].map(([key,a,e])=><Button type="button" variant="outline" key={key} onClick={()=>create(key)}>+ {t(a,e)}</Button>)}</div>
  {!groups.length&&<p className="rounded-xl border border-dashed p-6 text-center text-muted-foreground">{t('ابدأ بالمقاس أو اللون، أو أضف مجموعة باسمك.','Start with size or color, or add your own group.')}</p>}
  {groups.map((g,i)=><section className="rounded-xl border bg-white p-4 space-y-4" key={g.id||`new-${i}`} aria-label={g.name.ar||g.name.en||t('مجموعة خيارات','Option group')}>
   <div className="flex flex-wrap items-end gap-3"><label className="min-w-40 flex-1 text-sm font-medium">{t('اسم المجموعة','Group name')}<Input value={ar?g.name.ar:g.name.en} placeholder={t('مثال: المقاس','Example: Size')} onChange={e=>update(i,{name:{...g.name,[ar?'ar':'en']:e.target.value}})}/></label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={g.required} onChange={e=>update(i,{required:e.target.checked})}/>{t('اختيار إجباري','Required')}</label><Button type="button" variant="ghost" disabled={i===0} aria-label={t('تحريك المجموعة لأعلى','Move group up')} onClick={()=>{const next=[...groups];[next[i-1],next[i]]=[next[i],next[i-1]];onChange(next)}}>↑</Button><Button type="button" variant="ghost" className="text-red-700" onClick={()=>{if(window.confirm(t('حذف المجموعة وخياراتها من هذا المنتج؟','Remove this group and its options?')))onChange(groups.filter((_,j)=>j!==i))}}>{t('حذف','Remove')}</Button></div>
   <div className="flex flex-wrap gap-2"><Input className="min-w-52 flex-1" aria-label={t('إضافة خيارات دفعة واحدة','Add multiple options')} placeholder={g.option_type==='color'?t('أسود، أبيض، بيج','Black, White, Beige'):t('صغير، متوسط، كبير','Small, Medium, Large')} value={texts[i]||''} onChange={e=>setTexts({...texts,[i]:e.target.value})} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();update(i,appendVariantOptions(g,texts[i]||'',ar?'ar':'en'));setTexts({...texts,[i]:''})}}}/><Button type="button" onClick={()=>{update(i,appendVariantOptions(g,texts[i]||'',ar?'ar':'en'));setTexts({...texts,[i]:''})}}>{t('إضافة القيم','Add values')}</Button></div>
   {!!g.options.length&&<details className="rounded-lg bg-slate-50 p-3 text-sm"><summary className="cursor-pointer font-medium">{t('تعديل جماعي لهذه المجموعة','Bulk edit this group')}</summary><div className="mt-3 flex flex-wrap items-end gap-2"><label>{t('سعر جميع الخيارات','Price for all options')}<Input type="number" min="0" step="any" value={bulk[i]?.price||''} onChange={e=>setBulk({...bulk,[i]:{...bulk[i],price:e.target.value}})}/></label><Button type="button" variant="outline" disabled={!bulk[i]?.price} onClick={()=>update(i,{options:g.options.map(o=>({...o,price:Number(bulk[i].price)}))})}>{t('تطبيق السعر','Apply price')}</Button><Button type="button" variant="outline" onClick={()=>update(i,{options:g.options.map(o=>({...o,price:null}))})}>{t('استخدام سعر المنتج','Use product price')}</Button><label>{t('مخزون كل خيار','Stock per option')}<Input type="number" min="0" step="1" value={bulk[i]?.stock||''} onChange={e=>setBulk({...bulk,[i]:{...bulk[i],stock:e.target.value}})}/></label><Button type="button" variant="outline" disabled={!bulk[i]?.stock} onClick={()=>update(i,{options:g.options.map(o=>({...o,stock:Number(bulk[i].stock),manage_stock:true}))})}>{t('تطبيق المخزون','Apply stock')}</Button></div></details>}
   <div className="space-y-3">{g.options.map((o,j)=><article className="rounded-lg border p-3" key={o.id||`new-${j}`}>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><label className="text-xs font-medium">{t('الخيار','Option')}<Input value={ar?o.label.ar:o.label.en} onChange={e=>option(i,j,{label:{...o.label,[ar?'ar':'en']:e.target.value}})}/></label><label className="text-xs font-medium">{t('سعر هذا الخيار','Option price')}<Input type="number" min="0" step="any" value={o.price??''} placeholder={`${basePrice??''} · ${t('تلقائي','auto')}`} onChange={e=>option(i,j,{price:e.target.value===''?null:Number(e.target.value)})}/></label><label className="text-xs font-medium">{t('المخزون','Stock')}<Input type="number" min="0" step="1" disabled={!o.manage_stock} value={o.stock??''} placeholder={o.manage_stock?t('غير محدد','Unspecified'):'∞'} onChange={e=>option(i,j,{stock:e.target.value===''?null:Number(e.target.value)})}/></label><div className="flex flex-wrap items-center gap-3 text-xs"><label className="flex gap-1"><input type="checkbox" checked={o.manage_stock} onChange={e=>option(i,j,{manage_stock:e.target.checked})}/>{t('تتبع المخزون','Track stock')}</label><label className="flex gap-1"><input type="checkbox" checked={o.in_stock} onChange={e=>option(i,j,{in_stock:e.target.checked})}/>{t('متاح','Available')}</label></div></div>
    {g.option_type==='color'&&<label className="mt-2 flex items-center gap-2 text-xs">{t('لون الخيار','Swatch')}<input type="color" value={/^#[0-9a-f]{6}$/i.test(o.value)?o.value:'#64748b'} onChange={e=>option(i,j,{value:e.target.value})}/><Input className="max-w-40" dir="ltr" value={o.value} onChange={e=>option(i,j,{value:e.target.value})}/></label>}
    {g.option_type==='image'&&<label className="mt-2 flex items-center gap-3 text-xs">{o.value&&<img src={o.value} alt="" className="h-12 w-12 rounded object-cover"/>}{t('صورة الخيار','Option image')}<input type="file" accept="image/*" onChange={e=>onUpload(i,j,e)}/></label>}
    <div className="mt-2 flex flex-wrap items-center gap-3 text-xs"><label className="flex gap-1"><input type="checkbox" checked={o.is_default} onChange={e=>update(i,{options:g.options.map((x,k)=>({...x,is_default:k===j?e.target.checked:false}))})}/>{t('محدد افتراضيًا','Selected by default')}</label><button type="button" disabled={j===0} onClick={()=>{const options=[...g.options];[options[j-1],options[j]]=[options[j],options[j-1]];update(i,{options})}}>{t('تحريك لأعلى','Move up')} ↑</button><button type="button" className="ms-auto text-red-700 underline" onClick={()=>{if(window.confirm(t('حذف هذا الخيار؟','Remove this option?')))update(i,{options:g.options.filter((_,k)=>k!==j)})}}>{t('حذف الخيار','Remove option')}</button></div>
    <details className="mt-2 text-xs"><summary className="cursor-pointer text-muted-foreground">{t('الترجمة والقيمة والإعدادات القديمة','Translation, value and legacy settings')}</summary><div className="mt-3 grid gap-3 sm:grid-cols-2"><label>{ar?'English':'العربية'}<Input value={ar?o.label.en:o.label.ar} onChange={e=>option(i,j,{label:{...o.label,[ar?'en':'ar']:e.target.value}})}/></label>{g.option_type!=='color'&&<label>{t('القيمة المحفوظة / رابط الصورة','Stored value / image URL')}<Input value={o.value} onChange={e=>option(i,j,{value:e.target.value})}/></label>}<label>{t('فرق السعر عند اتباع سعر المنتج','Price adjustment when inheriting product price')}<Input type="number" step="any" value={o.price_modifier??0} onChange={e=>option(i,j,{price_modifier:Number(e.target.value)})}/></label>{o.stock_quantity!=null&&<label>{t('حقل المخزون القديم (محفوظ)','Legacy stock field (preserved)')}<Input type="number" value={o.stock_quantity} onChange={e=>option(i,j,{stock_quantity:Number(e.target.value)})}/></label>}</div></details>
   </article>)}</div>
   <details className="text-sm"><summary className="cursor-pointer font-medium">{t('طريقة العرض والترجمة','Display and translation')}</summary><div className="mt-3 grid gap-3 sm:grid-cols-3"><label>{ar?'English':'العربية'}<Input value={ar?g.name.en:g.name.ar} onChange={e=>update(i,{name:{...g.name,[ar?'en':'ar']:e.target.value}})}/></label><label>{t('نوع القيمة','Value type')}<select className="block w-full rounded border p-2" value={g.option_type} onChange={e=>update(i,{option_type:e.target.value})}>{[['text','نص','Text'],['color','لون','Color'],['image','صورة','Image']].map(([v,a,e])=><option key={v} value={v}>{t(a,e)}</option>)}</select></label><label>{t('طريقة الاختيار','Display style')}<select className="block w-full rounded border p-2" value={g.display_type} onChange={e=>update(i,{display_type:e.target.value})}>{[['buttons','أزرار','Buttons'],['list','قائمة','List'],['dropdown','قائمة منسدلة','Dropdown'],['color','ألوان','Swatches'],['image','صور','Images']].map(([v,a,e])=><option key={v} value={v}>{t(a,e)}</option>)}</select></label></div></details>
  </section>)}
 </div>;
}

