'use client';
import {useState,useEffect} from 'react';
import {createClient} from '@/lib/supabase/client';
import {useLanguage} from '@/contexts/LanguageContext';
import {loadVariantEditor,saveVariantEditor,VariantEditorGroup} from '@/lib/variant-editor';
import {QuickVariantEditor} from './QuickVariantEditor';
import {Button} from '@/components/ui/button';
import {toast} from 'sonner';
interface Props {productId?:string;value?:VariantEditorGroup[];onChange?:(v:VariantEditorGroup[])=>void;standalone?:boolean;storeId?:string;basePrice?:string|number;baseStock?:string|number;globalIgnoreStock?:boolean;loading?:boolean;onReload?:()=>void}
export function VariantEditor({productId,value,onChange,standalone=true,storeId,basePrice,globalIgnoreStock,loading:externalLoading=false,onReload}:Props){
 const {language}=useLanguage();const ar=language==='ar';const db=createClient();const [local,setLocal]=useState<VariantEditorGroup[]>([]);const [revision,setRevision]=useState<number|null>(productId?null:0);const [loading,setLoading]=useState(false);const [saving,setSaving]=useState(false);const [error,setError]=useState('');const [uploading,setUploading]=useState(false);
 const groups=value??local;const change=(v:VariantEditorGroup[])=>{setLocal(v);onChange?.(v)};
 const load=async()=>{if(!productId)return;setLoading(true);setError('');try{const r=await loadVariantEditor(db,productId);change(r.variants);setRevision(r.revision)}catch(e:any){setError(e.message||'تعذر تحميل الخيارات')}finally{setLoading(false)}};
 useEffect(()=>{if(standalone&&productId)load()},[productId,standalone]);
 const save=async()=>{if(!productId)return;setSaving(true);try{await saveVariantEditor(db,productId,groups,revision);await load();toast.success(ar?'تم حفظ الخيارات دون إعادة إنشاء معرّفاتها':'Options saved')}catch(e:any){toast.error(e.message)}finally{setSaving(false)}};
 const upload=async(g:number,o:number,e:React.ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];if(!file)return;if(!storeId){toast.error(ar?'اختر متجرًا أولًا':'A store is required');return}if(!['image/jpeg','image/png','image/webp','image/gif'].includes(file.type)||file.size>5*1024*1024){toast.error(ar?'اختر صورة PNG أو JPG أو WebP أو GIF لا تتجاوز 5 ميجابايت':'Use a JPG, PNG, WebP or GIF up to 5 MB');return}setUploading(true);try{const ext=file.type.split('/')[1];const name=`${storeId}/${crypto.randomUUID()}.${ext}`;const {error}=await db.storage.from('product-images').upload(name,file);if(error)throw error;const {data}=db.storage.from('product-images').getPublicUrl(name);change(groups.map((group,i)=>i===g?{...group,options:group.options.map((opt,j)=>j===o?{...opt,value:data.publicUrl}:opt)}:group))}catch(e:any){toast.error(e.message)}finally{setUploading(false);e.target.value=''}};
 return <section className="space-y-4" aria-label={ar?'خيارات المنتج':'Product options'}><div><h3 className="text-lg font-bold">{ar?'خيارات المنتج':'Product options'}</h3><p className="text-sm text-muted-foreground">{ar?'الألوان والمقاسات والأسعار والمخزون، في مكان واحد.':'Colors, sizes, prices and stock in one place.'}</p></div>{globalIgnoreStock&&<p className="rounded border border-amber-200 bg-amber-50 p-3 text-sm">{ar?'المنتج يسمح بالطلب عند نفاد المخزون. إعدادات كل خيار محفوظة وتعود للعمل عند إيقاف ذلك.':'This product allows ordering beyond stock; individual stock settings are preserved.'}</p>}{(loading||externalLoading)?<div role="status" className="p-6 text-center">{ar?'جاري تحميل الخيارات المحفوظة…':'Loading saved options…'}{onReload&&<Button type="button" variant="outline" onClick={onReload}>{ar?'إعادة المحاولة':'Retry'}</Button>}</div>:error?<div role="alert">{error}<Button type="button" onClick={load}>{ar?'إعادة المحاولة':'Retry'}</Button></div>:<fieldset disabled={saving||uploading} className="min-w-0"><QuickVariantEditor groups={groups} onChange={change} ar={ar} basePrice={basePrice} onUpload={upload}/></fieldset>}{uploading&&<p role="status">{ar?'جاري رفع الصورة…':'Uploading image…'}</p>}{standalone&&productId&&<Button type="button" disabled={loading||saving||uploading||revision===null} onClick={save}>{saving?(ar?'جاري الحفظ…':'Saving…'):(ar?'حفظ الخيارات':'Save options')}</Button>}</section>;
}
