export const governorates = [
    { id: 'cairo', ar: 'القاهرة', en: 'Cairo' },
    { id: 'giza', ar: 'الجيزة', en: 'Giza' },
    { id: 'alexandria', ar: 'الإسكندرية', en: 'Alexandria' },
    { id: 'dakahlia', ar: 'الدقهلية', en: 'Dakahlia' },
    { id: 'red_sea', ar: 'البحر الأحمر', en: 'Red Sea' },
    { id: 'beheira', ar: 'البحيرة', en: 'Beheira' },
    { id: 'fayoum', ar: 'الفيوم', en: 'Fayoum' },
    { id: 'gharbia', ar: 'الغربية', en: 'Gharbia' },
    { id: 'ismailia', ar: 'الإسماعيلية', en: 'Ismailia' },
    { id: 'monufia', ar: 'المنوفية', en: 'Monufia' },
    { id: 'minya', ar: 'المنيا', en: 'Minya' },
    { id: 'qalyubia', ar: 'القليوبية', en: 'Qalyubia' },
    { id: 'new_valley', ar: 'الوادي الجديد', en: 'New Valley' },
    { id: 'suez', ar: 'السويس', en: 'Suez' },
    { id: 'aswan', ar: 'أسوان', en: 'Aswan' },
    { id: 'assiut', ar: 'أسيوط', en: 'Assiut' },
    { id: 'beni_suef', ar: 'بني سويف', en: 'Beni Suef' },
    { id: 'port_said', ar: 'بورسعيد', en: 'Port Said' },
    { id: 'damietta', ar: 'دمياط', en: 'Damietta' },
    { id: 'sharkia', ar: 'الشرقية', en: 'Sharkia' },
    { id: 'south_sinai', ar: 'جنوب سيناء', en: 'South Sinai' },
    { id: 'kafr_el_sheikh', ar: 'كفر الشيخ', en: 'Kafr El Sheikh' },
    { id: 'matrouh', ar: 'مطروح', en: 'Matrouh' },
    { id: 'luxor', ar: 'الأقصر', en: 'Luxor' },
    { id: 'qena', ar: 'قنا', en: 'Qena' },
    { id: 'north_sinai', ar: 'شمال سيناء', en: 'North Sinai' },
    { id: 'sohag', ar: 'سوهاج', en: 'Sohag' },
];
