'use client';
import {useState,CSSProperties} from 'react';
import Link from 'next/link';
import {ArrowUpLeft,ArrowUpRight,ShoppingBag,Search,Menu,X,Plus,Package} from 'lucide-react';
import {useLanguage} from '@/contexts/LanguageContext';
import {useOptionalCart} from '@/contexts/CartContext';
import {localizedValue,productImages,safeThemeUrl,studioTheme} from '@/lib/theme-studio';
import styles from './storefront.module.css';

export function StudioSection({type,settings={},blocks=[],storeContext={}}:{type:string;settings?:Record<string,any>;blocks?:any[];storeContext?:any}) {
 const {language}=useLanguage();const ar=language==='ar';const t=(a:string,e:string)=>ar?a:e;const cart=useOptionalCart();const [menu,setMenu]=useState(false);const [query,setQuery]=useState('');const [adding,setAdding]=useState<string|null>(null);
 const store=storeContext.store||{};const tokens=storeContext.themeTokens||{};const theme=studioTheme(tokens.studio_theme||settings.theme_style||'default');const preview=!!storeContext.isEditorPreview||!!storeContext.isCatalogPreview;const base=store.baseUrl??(store.slug?`/s/${store.slug}`:'');
 const link=(path:string)=>preview?'#':path.startsWith('/')&&!path.startsWith('//')?`${base}${path==='/'?'':path}`:safeThemeUrl(path);
 const title=localizedValue(store.name,language)||t('متجرك','Your store');const description=localizedValue(store.description,language);const products=storeContext.products||storeContext.productsContext?.initialProducts||[];const categories=storeContext.categories||storeContext.headerCategories||[];const arrow=ar?<ArrowUpLeft size={18}/>:<ArrowUpRight size={18}/>;
 const number=(value:any,fallback:number,min:number,max:number)=>Math.max(min,Math.min(max,Number.isFinite(Number(value))?Number(value):fallback));
 const color=(value:string,fallback:string)=>/^#[0-9a-f]{6}$/i.test(value||'')?value:fallback;
 const style={ '--studio-primary':color(tokens.studio_primary,theme.primary),'--studio-bg':color(tokens.studio_background,theme.background),'--studio-ink':color(tokens.studio_ink,theme.ink),'--studio-soft':color(tokens.studio_soft,theme.soft),'--studio-radius':`${number(tokens.studio_radius,Number(theme.radius),0,40)}px`,'--studio-width':`${number(tokens.studio_width,1240,960,1600)}px`,'--studio-base':`${number(tokens.studio_base_size,16,14,20)}px`,'--studio-font':['Arial','Georgia'].includes(tokens.studio_font)?tokens.studio_font:'var(--font-tajawal)','--section-padding':`${number(settings.padding,48,0,120)}px`,'--heading-size':`${number(settings.heading_size,52,28,88)}px`,'--studio-columns':number(settings.columns,4,2,5),'--studio-image-fit':settings.image_fit==='contain'?'contain':'cover' } as CSSProperties;
 const money=(value:number)=>new Intl.NumberFormat(ar?'ar-EG':'en',{style:'currency',currency:store.currency||'EGP',maximumFractionDigits:2}).format(value);
 const image=(src:string,alt='',className='')=>src?<img src={safeThemeUrl(src,'')} alt={alt} loading="lazy" className={className}/>:<div className={styles.placeholder}><Package aria-hidden="true"/></div>;
 const heading=(fallback:string)=>localizedValue(settings.heading,language)||fallback;const subheading=localizedValue(settings.subheading,language);
 const productLink=(p:any)=>link(`/${p.id}`);
 const add=async(p:any)=>{if(preview||!cart)return;setAdding(p.id);try{const price=Number(p.sale_price)>0&&Number(p.sale_price)<Number(p.price)?Number(p.sale_price):Number(p.price);await cart.addToCart({productId:p.id,productName:typeof p.name==='object'?p.name:{ar:localizedValue(p.name,'ar'),en:localizedValue(p.name,'en')},productImage:productImages(p.images)[0]||null,basePrice:price,unitPrice:price,quantity:1,variants:[],addedAt:new Date().toISOString()})}finally{setAdding(null)}};
 let content:React.ReactNode=null;
 if(type==='header')content=<div className={`${styles.header} ${settings.sticky?styles.sticky:''}`}>{settings.notice_text&&<div className={styles.notice}>{localizedValue(settings.notice_text,language)}</div>}<div className={styles.inner}><Link href={link('/')} className={styles.brand}>{(settings.logo||store.logo_url)&&<img src={safeThemeUrl(settings.logo||store.logo_url,'')} alt=""/>}<span>{title}</span></Link><nav className={styles.nav} aria-label={t('تنقل المتجر','Store navigation')}><Link href={link('/')}>{t('الرئيسية','Home')}</Link><Link href={link('/products')}>{t('كل المنتجات','Shop all')}</Link>{blocks.filter(b=>b.settings?.label&&b.settings?.url).slice(0,3).map((b,i)=><Link key={i} href={link(b.settings.url)}>{localizedValue(b.settings.label,language)}</Link>)}</nav><div className={styles.tools}>{settings.show_search!==false&&<form className={styles.search} onSubmit={e=>{e.preventDefault();if(!preview)location.href=link(`/products?q=${encodeURIComponent(query)}`)}}><input aria-label={t('البحث في المنتجات','Search products')} value={query} onChange={e=>setQuery(e.target.value)} placeholder={t('ابحث عن منتج','Search products')}/><button aria-label={t('بحث','Search')}><Search size={18}/></button></form>}{settings.show_cart!==false&&<button type="button" className={styles.icon} aria-label={t('افتح السلة','Open cart')} onClick={()=>{if(!preview)cart?.openCart()}}><ShoppingBag size={19}/>{!!cart?.cartCount&&!preview&&<span className={styles.count}>{cart.cartCount}</span>}</button>}<button type="button" className={`${styles.icon} ${styles.mobileMenu}`} aria-expanded={menu} aria-label={t('قائمة المتجر','Store menu')} onClick={()=>setMenu(!menu)}>{menu?<X size={19}/>:<Menu size={19}/>}</button></div></div>{menu&&<nav className={styles.mobileNav}><Link href={link('/')}>{t('الرئيسية','Home')}</Link><Link href={link('/products')}>{t('كل المنتجات','Shop all')}</Link>{blocks.filter(b=>b.settings?.label&&b.settings?.url).map((b,i)=><Link key={i} href={link(b.settings.url)}>{localizedValue(b.settings.label,language)}</Link>)}</nav>}</div>;
 if(type==='hero_banner'){const first=products.find((p:any)=>productImages(p.images).length);const heroImage=settings.image_source==='custom'?settings.image_url:productImages(first?.images)[0];content=<div className={`${styles.inner} ${styles.hero} ${styles[settings.layout||theme.layout]||''}`}><div className={styles.copy}><span className={styles.eyebrow}>{title}</span><h1>{heading(title)}</h1><p>{subheading||description||t('تعرّف على منتجاتنا واختر ما يناسبك.','Explore our collection and find what suits you.')}</p><Link className={styles.primary} href={link(settings.button_url||'/products')}>{localizedValue(settings.button_label,language)||t('اكتشف المنتجات','Explore the collection')}{arrow}</Link></div><div className={styles.visual}>{image(heroImage||'',first?localizedValue(first.name,language):'')}</div></div>}
 if(type==='category_slider'){const chosen=settings.source==='manual'?categories.filter((c:any)=>blocks.some(b=>b.settings?.category_id===c.id)):categories;content=chosen.length?<div className={styles.inner}><div className={styles.sectionTitle}><div><h2>{heading(t('تسوق حسب التصنيف','Explore categories'))}</h2>{subheading&&<p>{subheading}</p>}</div></div><div className={styles.categories}>{chosen.slice(0,number(settings.limit,8,1,24)).map((c:any)=><Link className={styles.category} key={c.id} href={link(`/products?category=${c.id}`)}>{c.image_url&&image(c.image_url)}<span>{localizedValue(c.name,language)}</span>{arrow}</Link>)}</div></div>:null}
 if(type==='featured_grid'){const chosen=settings.source==='manual'?blocks.map(b=>products.find((p:any)=>p.id===b.settings?.product_id)).filter(Boolean):products;content=<div className={styles.inner}><div className={styles.sectionTitle}><div><h2>{heading(t('منتجات تستحق اكتشافها','Discover the collection'))}</h2>{subheading&&<p>{subheading}</p>}</div><Link className={styles.textLink} href={link('/products')}>{t('عرض الكل','View all')}{arrow}</Link></div>{chosen.length?<div className={styles.grid}>{chosen.slice(0,number(settings.limit,8,1,40)).map((p:any)=>{const price=Number(p.price)||0;const sale=Number(p.sale_price)>0&&Number(p.sale_price)<price?Number(p.sale_price):null;return <article className={styles.product} key={p.id}><Link href={productLink(p)} className={`${styles.productImage} ${settings.image_ratio==='portrait'?styles.portrait:''}`}>{image(productImages(p.images)[0]||'',localizedValue(p.name,language))}</Link><h3><Link href={productLink(p)}>{localizedValue(p.name,language)}</Link></h3>{settings.show_price!==false&&<div className={styles.price}><span>{money(sale??price)}</span>{sale!==null&&<del>{money(price)}</del>}</div>}{settings.show_add!==false&&(p.skip_cart?<Link className={styles.add} href={productLink(p)}>{t('عرض المنتج والطلب','View product & order')}{arrow}</Link>:<button className={styles.add} disabled={adding===p.id} onClick={()=>add(p)}>{adding===p.id?t('جاري الإضافة…','Adding…'):t('أضف إلى السلة','Add to cart')}<Plus size={17}/></button>)}</article>})}</div>:<div className={styles.empty}><Package className="mx-auto mb-3"/><h3>{t('نعمل على تجهيز مجموعتنا','Our collection is on its way')}</h3><p>{t('ستظهر المنتجات هنا فور إضافتها إلى المتجر.','Products will appear here as soon as they are added.')}</p></div>}</div>}
 if(type==='footer'){const contact=store.settings?.public_contact||{};content=<footer className={styles.footer}><div className={styles.inner}><div className={styles.footerGrid}><div><Link className={styles.brand} href={link('/')}>{title}</Link>{(settings.body||description)&&<p>{localizedValue(settings.body,language)||description}</p>}</div><div><h3>{t('تصفح المتجر','Explore')}</h3><div className={styles.footerLinks}><Link href={link('/')}>{t('الرئيسية','Home')}</Link><Link href={link('/products')}>{t('كل المنتجات','All products')}</Link>{blocks.filter(b=>b.settings?.label&&b.settings?.url).map((b,i)=><Link key={i} href={link(b.settings.url)}>{localizedValue(b.settings.label,language)}</Link>)}</div></div>{settings.show_contact!==false&&(contact.email||contact.phone)&&<div><h3>{t('تواصل معنا','Get in touch')}</h3><div className={styles.footerLinks}>{contact.email&&<a href={`mailto:${contact.email}`}>{contact.email}</a>}{contact.phone&&<a href={`tel:${contact.phone}`} dir="ltr">{contact.phone}</a>}</div></div>}</div><div className={styles.bottom}><span>© {new Date().getFullYear()} {title}</span></div></div></footer>}
 if(type==='rich_text')content=<div className={`${styles.inner} ${styles.story}`} style={{textAlign:settings.alignment==='center'?'center':'start'}}>{settings.image_url&&image(settings.image_url,'')}<div>{settings.heading&&<h2>{heading('')}</h2>}<p>{localizedValue(settings.body,language)}</p></div></div>;
 if(type==='image_banner')content=<div className={styles.inner}><div className={styles.banner}>{settings.image_url&&image(settings.image_url,'')}<div><h2>{heading('')}</h2>{subheading&&<p>{subheading}</p>}{settings.button_label&&<Link className={styles.primary} href={link(settings.button_url||'/products')}>{localizedValue(settings.button_label,language)}{arrow}</Link>}</div></div></div>;
 if(type==='benefits'&&blocks.length)content=<div className={`${styles.inner} ${styles.benefits}`}>{blocks.map((b,i)=><div key={i}><h3>{localizedValue(b.settings?.title,language)}</h3><p>{localizedValue(b.settings?.body,language)}</p></div>)}</div>;
 return content?<div className={styles.surface} data-theme={theme.id} style={style} dir={ar?'rtl':'ltr'}>{content}</div>:null;
}
