'use client';
import {useEffect,useState,useRef} from 'react';
import Link from 'next/link';
import {loadVariantEditor} from '@/lib/variant-editor';
import {createClient} from '@/lib/supabase/client';
import {useLanguage} from '@/contexts/LanguageContext';
import {StudioDocument,makeStudioSection,normalizeStudioDocument,studioSectionLabels,localizedValue,productImages} from '@/lib/theme-studio';
import {publicSettings} from '@/lib/public-store';
import SidebarForm from '@/components/ThemeEngine/Customizer/SidebarForm';
import productSchema from '@/themes/default/sections/MainProduct/schema.json';
import checkoutSchema from '@/themes/default/sections/MainCheckout/schema.json';
import {toast} from 'sonner';

export default function StudioEditor({storeId}:{storeId:string}){
 const db=createClient();const {language}=useLanguage();const ar=language==='ar';const t=(a:string,e:string)=>ar?a:e;
 const [doc,setDoc]=useState<StudioDocument|null>(null);const [saved,setSaved]=useState('');const [theme,setTheme]=useState<any>(null);const [revision,setRevision]=useState(0);const [context,setContext]=useState<any>({});const [page,setPage]=useState('home');const [selected,setSelected]=useState('');const [tab,setTab]=useState('sections');const [width,setWidth]=useState('100%');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [history,setHistory]=useState<any[]>([]);const [undo,setUndo]=useState<StudioDocument[]>([]);const [redo,setRedo]=useState<StudioDocument[]>([]);const loading=useRef(false);
 const frame=useRef<HTMLIFrameElement>(null);
 const dirty=!!doc&&JSON.stringify(doc)!==saved;
 async function load(){if(loading.current)return;loading.current=true;setBusy(true);setError('');try{
  const [active,store,products,categories]=await Promise.all([db.from('store_themes').select('id,global_tokens').eq('store_id',storeId).eq('is_active',true).maybeSingle(),db.from('stores').select('id,name,description,logo_url,slug,currency,settings,has_removed_copyright').eq('id',storeId).single(),db.from('public_products').select('*').eq('store_id',storeId).eq('status','active').limit(500),db.from('categories').select('id,name,image_url').eq('store_id',storeId).eq('status','active').order('sort_order')]);
  for(const result of [active,store,products,categories])if(result.error)throw result.error;
  if(!active.data){setTheme(null);setError(t('اختر تصميمًا أولًا من معرض الثيمات.','Choose a theme first.'));return}
  setTheme(active.data);if(active.data.global_tokens?.studio_version!=='2')return;
  const {data,error}=await db.rpc('load_studio_draft',{p_theme:active.data.id});if(error)throw error;const parse=(v:any)=>{if(typeof v!=='string')return v;try{return JSON.parse(v)}catch{return {ar:v,en:v}}};
  const actualProducts=(products.data||[]).map(p=>({...p,name:parse(p.name),description:parse(p.description),images:productImages(p.images)}));
  const actualStore={...store.data,settings:publicSettings(store.data.settings),name:parse(store.data.name),description:parse(store.data.description)};
  const first=actualProducts[0];const options=first?await loadVariantEditor(db,first.id):{variants:[]};
  const offers=first?await db.from('upsell_offers').select('*').eq('product_id',first.id).eq('is_active',true):{data:[]};
  setContext({store:actualStore,products:actualProducts,categories:categories.data||[],product:first,variants:options.variants,upsellOffers:offers.data||[],productsContext:{store:actualStore,initialProducts:actualProducts,initialCategories:categories.data||[]},isEditorPreview:true});
  const past=await db.from('store_theme_history').select('id,created_at,document').eq('store_theme_id',active.data.id).order('created_at',{ascending:false}).limit(20);if(past.error)throw past.error;setHistory(past.data||[]);setDoc(data.document);setSaved(JSON.stringify(data.document));setRevision(data.revision);setSelected(data.document.pages.home.sections_order[0]);setUndo([]);setRedo([]);
 }catch(e:any){setError(e.message)}finally{setBusy(false);loading.current=false}}
 useEffect(()=>{load()},[storeId]);
 useEffect(()=>{if(!dirty)return;const guard=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue=''};window.addEventListener('beforeunload',guard);return()=>window.removeEventListener('beforeunload',guard)},[dirty]);
 const sendPreview=()=>{if(doc)frame.current?.contentWindow?.postMessage({type:'STUDIO_PREVIEW',payload:{pageData:normalizeStudioDocument(doc).pages[page],tokens:normalizeStudioDocument(doc).tokens,context,language}},location.origin)};
 useEffect(()=>{sendPreview();const receive=(e:MessageEvent)=>{if(e.origin!==location.origin||e.source!==frame.current?.contentWindow)return;if(e.data?.type==='STUDIO_READY')sendPreview();if(e.data?.type==='STUDIO_SELECT'){setSelected(e.data.sectionId);setTab('sections')}};window.addEventListener('message',receive);return()=>window.removeEventListener('message',receive)},[doc,page,context,language]);
 const change=(next:StudioDocument)=>{if(!doc)return;setUndo(old=>[...old.slice(-29),doc]);setRedo([]);setDoc(next)};
 const section=doc?.pages[page]?.sections_data[selected];
 const patch=(settings:Record<string,any>)=>{if(!doc||!section)return;change({...doc,pages:{...doc.pages,[page]:{...doc.pages[page],sections_data:{...doc.pages[page].sections_data,[selected]:{...section,settings:{...section.settings,...settings}}}}}})};
 const blocks=(items:any[])=>{if(!doc||!section)return;change({...doc,pages:{...doc.pages,[page]:{...doc.pages[page],sections_data:{...doc.pages[page].sections_data,[selected]:{...section,blocks:items}}}}})};
 async function save(publish=false){if(!doc||!theme)return;setBusy(true);try{const normalized=normalizeStudioDocument(doc);const {data,error}=await db.rpc('save_studio_draft',{p_theme:theme.id,p_document:normalized,p_revision:revision,p_publish:publish});if(error)throw error;setDoc(normalized);setSaved(JSON.stringify(normalized));setRevision(data.revision);toast.success(publish?t('تم نشر التصميم للزوار','Design published'):t('تم حفظ المسودة دون تغيير المتجر','Draft saved; storefront unchanged'));if(publish){const past=await db.from('store_theme_history').select('id,created_at,document').eq('store_theme_id',theme.id).order('created_at',{ascending:false}).limit(20);setHistory(past.data||[])}}catch(e:any){toast.error(e.message)}finally{setBusy(false)}}
 async function upload(file:File){if(!['image/jpeg','image/png','image/webp','image/gif'].includes(file.type)||file.size>5*1024*1024){toast.error(t('الصورة يجب أن تكون JPG أو PNG أو WebP أو GIF وأقل من 5 ميجابايت','Use JPG, PNG, WebP or GIF under 5 MB'));return}setBusy(true);try{const name=`${storeId}/theme-${crypto.randomUUID()}.${file.type.split('/')[1]}`;const {error}=await db.storage.from('product-images').upload(name,file);if(error)throw error;patch({image_url:db.storage.from('product-images').getPublicUrl(name).data.publicUrl,image_source:'custom'})}catch(e:any){toast.error(e.message)}finally{setBusy(false)}}
 const field=(key:string,label:string,type='text',placeholder='')=><label className="block space-y-1 text-sm" key={key}><span>{label}</span><input className="w-full rounded-lg border bg-white px-3 py-2" type={type} value={section?.settings[key]??''} placeholder={placeholder} onChange={e=>patch({[key]:type==='number'?Number(e.target.value):e.target.value})}/></label>;
 const check=(key:string,label:string)=><label key={key} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={section?.settings[key]!==false} onChange={e=>patch({[key]:e.target.checked})}/>{label}</label>;
 const select=(key:string,label:string,options:string[][])=><label key={key} className="block space-y-1 text-sm">{label}<select className="w-full rounded-lg border p-2" value={section?.settings[key]||options[0][0]} onChange={e=>patch({[key]:e.target.value})}>{options.map(([value,name])=><option key={value} value={value}>{name}</option>)}</select></label>;
 if(!doc)return <div className="space-y-4 p-8">{busy?<p role="status">{t('جاري تحميل تصميمك…','Loading your design…')}</p>:error?<p role="alert">{error}</p>:theme?.global_tokens?.studio_version!=='2'?<><h1 className="text-2xl font-bold">{t('تصميمك الحالي محفوظ','Your current design is preserved')}</h1><p>{t('يمكنك تعديله بالمحرر السابق أو اختيار تصميم جديد يستخدم بيانات متجرك تلقائيًا.','Edit it with the previous editor, or choose a new design that uses your store data automatically.')}</p><Link className="block underline" href={`/dashboard/${storeId}/editor/legacy`}>{t('تعديل التصميم الحالي','Edit current design')}</Link></>:null}<Link className="underline" href={`/dashboard/${storeId}/themes`}>{t('معرض الثيمات','Theme gallery')}</Link>{error&&<button onClick={load} className="ms-4 underline">{t('إعادة المحاولة','Retry')}</button>}</div>;
 return <div dir={ar?'rtl':'ltr'} className="min-h-screen bg-slate-100 text-slate-900"><header className="sticky top-0 z-30 flex flex-wrap items-center justify-between gap-3 border-b bg-white p-4"><div><Link href={`/dashboard/${storeId}/themes`} className="text-sm text-teal-700">{t('← الثيمات','← Themes')}</Link><h1 className="font-bold">{t('استوديو تصميم المتجر','Store design studio')}</h1><span role="status" className="text-xs text-slate-500">{dirty?t('تغييرات غير محفوظة','Unsaved changes'):t('المسودة محفوظة','Draft saved')}</span></div><div className="flex flex-wrap gap-2"><button disabled={!undo.length||busy} className="rounded-lg border px-3 py-2 disabled:opacity-40" onClick={()=>{setRedo([doc,...redo]);setDoc(undo[undo.length-1]);setUndo(undo.slice(0,-1))}}>{t('تراجع','Undo')}</button><button disabled={!redo.length||busy} className="rounded-lg border px-3 py-2 disabled:opacity-40" onClick={()=>{setUndo([...undo,doc]);setDoc(redo[0]);setRedo(redo.slice(1))}}>{t('إعادة','Redo')}</button><button disabled={busy} className="rounded-lg border px-3 py-2" onClick={()=>save(false)}>{t('حفظ مسودة','Save draft')}</button><button disabled={busy} className="rounded-lg bg-teal-700 px-5 py-2 text-white" onClick={()=>save(true)}>{busy?t('جاري الحفظ…','Saving…'):t('نشر التصميم','Publish design')}</button></div></header>
 <div className="grid lg:grid-cols-[340px_minmax(0,1fr)]"><aside {...(busy?{inert:''} as any:{})} className="space-y-5 border-e bg-white p-4 lg:max-h-[calc(100vh-90px)] lg:overflow-y-auto"><div className="flex gap-2">{[['sections','الأقسام','Sections'],['brand','الهوية','Brand'],['history','الإصدارات','History']].map(([id,a,e])=><button key={id} onClick={()=>setTab(id)} className={`flex-1 rounded-lg p-2 text-sm ${tab===id?'bg-teal-100 text-teal-900':'bg-slate-100'}`}>{t(a,e)}</button>)}</div>
 {tab==='brand'?<div className="space-y-4"><p className="text-sm text-slate-500">{t('اسم المتجر وشعاره من إعداداته، والمنتجات والتصنيفات تُجلب تلقائيًا.','Store name and logo come from settings. Products and categories fill automatically.')}</p>{[['studio_primary','اللون الأساسي','Primary'],['studio_background','الخلفية','Background'],['studio_ink','النص','Text'],['studio_soft','الخلفية الثانوية','Soft background']].map(([key,a,e])=><label key={key} className="flex items-center justify-between gap-3 text-sm">{t(a,e)}<input type="color" value={doc.tokens[key]} onChange={ev=>change({...doc,tokens:{...doc.tokens,[key]:ev.target.value}})}/></label>)}{[['studio_radius','استدارة الحواف','Corner radius',0,40],['studio_width','عرض المحتوى','Content width',960,1600],['studio_base_size','حجم الخط','Font size',14,20]].map(([key,a,e,min,max])=><label key={String(key)} className="block text-sm">{t(String(a),String(e))}: {doc.tokens[String(key)]}<input className="w-full" type="range" min={min} max={max} value={doc.tokens[String(key)]} onChange={ev=>change({...doc,tokens:{...doc.tokens,[String(key)]:ev.target.value}})}/></label>)}<label className="block text-sm">{t('الخط','Font')}<select className="w-full rounded border p-2" value={doc.tokens.studio_font} onChange={e=>change({...doc,tokens:{...doc.tokens,studio_font:e.target.value}})}>{['Tajawal','Arial','Georgia'].map(f=><option key={f}>{f}</option>)}</select></label><Link className="block text-sm underline" href={`/dashboard/${storeId}/settings`}>{t('تعديل بيانات المتجر والشعار','Edit store identity')}</Link></div>:tab==='history'?<div className="space-y-3"><p className="text-sm">{t('استرجاع إصدار يضعه في المسودة. راجعه ثم انشره.','Restore into the draft, review, then publish.')}</p>{!history.length&&<p className="text-sm text-slate-500">{t('تظهر الإصدارات السابقة بعد أول نشر.','Versions appear after your first publish.')}</p>}{history.map(h=><button className="block w-full rounded-lg border p-3 text-start" key={h.id} onClick={()=>{change(h.document);toast.info(t('تم تحميل الإصدار في المسودة','Version loaded into draft'))}}>{new Date(h.created_at).toLocaleString(ar?'ar-EG':'en')}</button>)}</div>:<><label className="block text-sm">{t('الصفحة','Page')}<select aria-label={t("الصفحة","Page")} className="mt-1 w-full rounded-lg border p-2" value={page} onChange={e=>{setPage(e.target.value);setSelected(doc.pages[e.target.value].sections_order.find(id=>!['header','footer'].includes(doc.pages[e.target.value].sections_data[id].type))||doc.pages[e.target.value].sections_order[0])}}>{[['home','الرئيسية','Home'],['product','المنتج','Product'],['products','قائمة المنتجات','Products'],['checkout','إتمام الطلب','Checkout']].map(([id,a,e])=><option key={id} value={id}>{t(a,e)}</option>)}</select></label>
 <div className="space-y-2">{doc.pages[page].sections_order.map((id,i)=>{const s=doc.pages[page].sections_data[id];const shared=page!=='home'&&['header','footer'].includes(s.type);return <div key={id} className={`flex items-center gap-1 rounded-lg border p-2 ${selected===id?'border-teal-600 bg-teal-50':''}`}><button className="flex-1 text-start text-sm" onClick={()=>{if(shared)setPage('home');setSelected(id)}}>{studioSectionLabels[s.type]?.[ar?0:1]||s.type}{s.hidden?' · '+t('مخفي','Hidden'):''}{shared?' ↗':''}</button>{!shared&&<button className="px-2" disabled={i===0} aria-label={t('تحريك القسم لأعلى','Move section up')} onClick={()=>{const order=[...doc.pages[page].sections_order];[order[i-1],order[i]]=[order[i],order[i-1]];change({...doc,pages:{...doc.pages,[page]:{...doc.pages[page],sections_order:order}}})}}>↑</button>}</div>})}</div>
 <select aria-label={t('إضافة قسم','Add section')} className="w-full rounded-lg border p-2" value="" onChange={e=>{if(!e.target.value)return;const type=e.target.value;const id=`${type}_${crypto.randomUUID()}`;const p=doc.pages[page];const order=[...p.sections_order];const footer=order.findIndex(x=>p.sections_data[x].type==='footer');order.splice(footer<0?order.length:footer,0,id);change({...doc,pages:{...doc.pages,[page]:{sections_order:order,sections_data:{...p.sections_data,[id]:makeStudioSection(type,doc.tokens.studio_theme)}}}});setSelected(id)}}><option value="">+ {t('إضافة قسم','Add section')}</option>{['hero_banner','featured_grid','category_slider','rich_text','image_banner','benefits'].map(type=><option key={type} value={type}>{studioSectionLabels[type][ar?0:1]}</option>)}</select>
 {section&&<fieldset disabled={busy} className="min-w-0 space-y-4 border-t pt-4"><h2 className="font-bold">{studioSectionLabels[section.type]?.[ar?0:1]}</h2>{!section.type.startsWith('main_')&&<><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={!section.hidden} onChange={e=>change({...doc,pages:{...doc.pages,[page]:{...doc.pages[page],sections_data:{...doc.pages[page].sections_data,[selected]:{...section,hidden:!e.target.checked}}}}})}/>{t('إظهار القسم','Show section')}</label>{field('heading',t('العنوان — اتركه فارغًا للنص التلقائي','Heading — blank uses automatic text'))}{field('subheading',t('الوصف المختصر','Subtitle'))}{field('padding',t('المسافة الرأسية','Vertical spacing'),'number')}
 {['hero_banner','rich_text','image_banner'].includes(section.type)&&<>{field('image_url',t('رابط الصورة','Image URL'))}<label className="block text-sm">{t('أو ارفع صورة','Or upload an image')}<input className="mt-1 w-full text-xs" type="file" accept="image/png,image/jpeg,image/webp,image/gif" onChange={e=>{const file=e.target.files?.[0];if(file)upload(file)}}/></label>{section.type==='hero_banner'&&<>{select('image_source',t('مصدر الصورة','Image source'),[['auto',t('تلقائي من المنتجات','Automatic from products')],['custom',t('صورة مخصصة','Custom image')]])}{select('layout',t('تخطيط الواجهة','Hero layout'),[['split',t('صورة ونص متجاوران','Split')],['editorial',t('تصميم مجلة','Editorial')],['centered',t('توسيط المحتوى','Centered')],['bold',t('بارز','Bold')],['compact',t('مختصر','Compact')],['playful',t('مرح','Playful')],['journal',t('قصة مصورة','Journal')],['showcase',t('عرض مميز','Showcase')],['soft',t('ناعم','Soft')]])}{field('heading_size',t('حجم العنوان','Heading size'),'number')}</>}{section.type!=='rich_text'&&<>{field('button_label',t('نص الزر','Button label'))}{field('button_url',t('رابط الزر','Button link'))}</>}</>}
 {['rich_text','footer'].includes(section.type)&&<label className="block text-sm">{t('النص','Body')}<textarea className="min-h-24 w-full rounded-lg border p-2" value={section.settings.body||''} onChange={e=>patch({body:e.target.value})}/></label>}
 {section.type==='header'&&<>{field('notice_text',t('شريط التنبيه — اختياري','Announcement — optional'))}{check('show_search',t('إظهار البحث','Show search'))}{check('show_cart',t('إظهار السلة','Show cart'))}</>}
 {section.type==='footer'&&check('show_contact',t('بيانات التواصل العامة','Public contact details'))}
 {['featured_grid','category_slider'].includes(section.type)&&<>{select('source',t('المحتوى','Content'),[['auto',t('تلقائي من المتجر','Automatic from store')],['manual',t('أختار بنفسي','Choose items')]])}{field('limit',t('عدد العناصر','Item count'),'number')}{section.settings.source==='manual'&&<div className="max-h-52 space-y-2 overflow-y-auto rounded border p-2">{(section.type==='featured_grid'?context.products:context.categories).map((item:any)=>{const key=section.type==='featured_grid'?'product_id':'category_id';return <label key={item.id} className="flex gap-2 text-sm"><input type="checkbox" checked={section.blocks.some(b=>b.settings?.[key]===item.id)} onChange={e=>blocks(e.target.checked?[...section.blocks,{type:'item',settings:{[key]:item.id}}]:section.blocks.filter(b=>b.settings?.[key]!==item.id))}/>{localizedValue(item.name,language)}</label>})}</div>}{section.type==='featured_grid'&&<>{field('columns',t('أعمدة الكمبيوتر','Desktop columns'),'number')}{select('image_ratio',t('نسبة الصورة','Image shape'),[['square',t('مربعة','Square')],['portrait',t('طولية','Portrait')]])}{select('image_fit',t('طريقة عرض الصورة','Image fit'),[['cover',t('ملء المساحة','Fill')],['contain',t('الصورة كاملة','Contain')]])}{check('show_price',t('السعر','Price'))}{check('show_add',t('زر الشراء','Purchase button'))}</>}</>}
 {['header','footer','benefits'].includes(section.type)&&<div className="space-y-3"><h3 className="text-sm font-medium">{section.type==='benefits'?t('معلومات الخدمة','Service details'):t('روابط إضافية','Extra links')}</h3>{section.blocks.map((b,i)=><div className="space-y-2 rounded border p-2" key={i}>{(section.type==='benefits'?['title','body']:['label','url']).map(key=><input key={key} aria-label={key} placeholder={key} className="w-full rounded border p-2 text-sm" value={b.settings?.[key]||''} onChange={e=>blocks(section.blocks.map((x,j)=>j===i?{...x,settings:{...x.settings,[key]:e.target.value}}:x))}/>)}<button type="button" className="text-xs text-red-700" onClick={()=>blocks(section.blocks.filter((_,j)=>j!==i))}>{t('حذف','Remove')}</button></div>)}<button type="button" className="text-sm underline" onClick={()=>blocks([...section.blocks,{type:'item',settings:{}}])}>+ {t('إضافة','Add')}</button></div>}
 <button className="text-sm text-red-700 underline" onClick={()=>{if(!confirm(t('حذف القسم من المسودة؟ يمكنك التراجع.','Remove this section from the draft? You can undo.')))return;const p=doc.pages[page];const data={...p.sections_data};delete data[selected];change({...doc,pages:{...doc.pages,[page]:{sections_order:p.sections_order.filter(x=>x!==selected),sections_data:data}}});setSelected('')}}>{t('حذف القسم','Remove section')}</button></>}
 {section.type==='main_product'&&<>{select('product_layout',t('تخطيط المنتج','Product layout'),[['gallery_right',t('الصورة في البداية','Image first')],['gallery_left',t('الصورة في الجانب الآخر','Image opposite')],['stacked',t('عرض متتابع','Stacked')]])}{select('image_ratio',t('نسبة الصورة','Image shape'),[['square',t('مربعة','Square')],['portrait',t('طولية','Portrait')]])}{select('image_fit',t('ملاءمة الصورة','Image fit'),[['cover',t('ملء المساحة','Fill')],['contain',t('الصورة كاملة','Contain')]])}</>}{section.type==='main_checkout'&&select('layout',t('تخطيط الطلب','Checkout layout'),[['split',t('نموذج وملخص متجاوران','Side by side')],['stacked',t('عرض متتابع','Stacked')]])}{section.type==='main_products'&&select('columns',t('أعمدة المنتجات','Product columns'),[['2','2'],['3','3'],['4','4']])}{['main_product','main_checkout'].includes(section.type)&&<SidebarForm sectionId={selected} schema={section.type==='main_product'?productSchema:checkoutSchema} settings={section.settings} blocks={section.blocks} onChange={(_,key,value)=>patch({[key]:value})} onBlockChange={(_,i,key,value)=>blocks(section.blocks.map((b,j)=>j===i?{...b,settings:{...b.settings,[key]:value}}:b))} onAddBlock={(_,type)=>blocks([...section.blocks,{type,settings:{}}])} onRemoveBlock={(_,i)=>blocks(section.blocks.filter((_,j)=>j!==i))} onReorderBlocks={(_,a,b)=>{const items=[...section.blocks];const [item]=items.splice(a,1);items.splice(b,0,item);blocks(items)}} onColorChange={(key,value)=>change({...doc,tokens:{...doc.tokens,[key]:value}})} globalTokens={doc.tokens} storeId={storeId}/>}
 </fieldset>}</>}
 </aside><main className="min-w-0 space-y-4 p-3 md:p-6"><div className="flex flex-wrap items-center justify-between gap-3"><p className="text-sm text-slate-600">{t('معاينة من بيانات متجرك — النشر فقط يغيّر ما يراه الزوار','Preview uses your store data. Only publishing changes the storefront.')}</p><div className="flex gap-1">{[['100%','كمبيوتر','Desktop'],['768px','تابلت','Tablet'],['390px','هاتف','Mobile']].map(([size,a,e])=><button className={`rounded border px-3 py-2 text-xs ${width===size?'bg-slate-900 text-white':'bg-white'}`} key={size} onClick={()=>setWidth(size)}>{t(a,e)}</button>)}</div></div><div className="mx-auto max-w-full overflow-hidden rounded-xl bg-white shadow-sm ring-1 ring-slate-200" style={{width}} onClickCapture={e=>{const target=(e.target as HTMLElement).closest('[data-studio-section]');if(target){setSelected(target.getAttribute('data-studio-section')||'');setTab('sections')}}}><iframe ref={frame} title={t('معاينة المتجر','Store preview')} src="/studio-preview" onLoad={sendPreview} className="h-[78vh] min-h-[600px] w-full border-0"/>{page!=='home'&&<div className="border-t p-4 text-center text-sm text-slate-500">{t('الشراء وإتمام الطلب يعملان في المتجر المنشور. هذه المعاينة لا تنشئ طلبات أو تعدّل السلة.','Purchasing works on the published store. This preview does not create orders or change the cart.')}<Link className="ms-2 underline" target="_blank" href={`/s/${context.store?.slug}${page==='products'?'/products':page==='checkout'?'/checkout':context.products?.[0]?`/${context.products[0].id}`:''}`}>{t('فتح الصفحة المنشورة','Open published page')}</Link></div>}</div></main></div></div>;
}


