'use client';
import {useState,useEffect} from 'react';
import Link from 'next/link';
import {createClient} from '@/lib/supabase/client';
import {studioThemes} from '@/lib/theme-studio';
import {useLanguage} from '@/contexts/LanguageContext';
import {toast} from 'sonner';
export default function ThemeGallery({storeId}:{storeId:string}){
 const db=createClient();const {language}=useLanguage();const ar=language==='ar';const [active,setActive]=useState<any>();const [busy,setBusy]=useState('');const [error,setError]=useState('');const [saved,setSaved]=useState<any[]>([]);
 async function load(){const {data,error}=await db.from('store_themes').select('id,global_tokens,theme_versions(version,themes(folder_name))').eq('store_id',storeId).eq('is_active',true).maybeSingle();if(error)setError(error.message);else setActive(data);const previous=await db.from('store_themes').select('id,global_tokens,theme_versions(version,themes(folder_name,name))').eq('store_id',storeId).eq('is_active',false);if(previous.error)setError(previous.error.message);else setSaved(previous.data||[])}
 useEffect(()=>{load()},[storeId]);
 async function activate(folder:string){setBusy(folder);try{const {error}=await db.rpc('activate_studio_theme',{p_store:storeId,p_folder:folder});if(error)throw error;await load();toast.success(ar?'تم تطبيق التصميم باستخدام بيانات متجرك':'Design applied using your store data')}catch(e:any){toast.error(e.message)}finally{setBusy('')}}
 async function restore(id:string){setBusy(id);try{const {error}=await db.rpc('restore_saved_store_theme',{p_store:storeId,p_theme:id});if(error)throw error;await load();toast.success(ar?'تم استعادة تصميمك المحفوظ':'Saved design restored')}catch(e:any){toast.error(e.message)}finally{setBusy('')}}
 return <div className="mx-auto max-w-7xl space-y-8 p-4 md:p-8" dir={ar?'rtl':'ltr'}><header className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-sm font-medium text-teal-700">ORDERLY STUDIO</p><h1 className="mt-2 text-3xl font-bold">{ar?'تصميم يشبه متجرك':'A design that feels like your store'}</h1><p className="mt-3 max-w-2xl text-muted-foreground">{ar?'اختر التصميم؛ تظهر منتجاتك وتصنيفاتك وهويتك تلقائيًا. بيانات العرض تخص المعاينة فقط، وتصميمك السابق يظل محفوظًا.':'Choose a design. Your products, categories and identity fill it automatically. Demo content stays in previews; your previous design is retained.'}</p></div>{active&&<Link className="rounded-xl bg-teal-700 px-5 py-3 text-white" href={`/dashboard/${storeId}/editor`}>{ar?'تخصيص التصميم الحالي':'Customize current design'}</Link>}</header>{error&&<p role="alert">{error}</p>}
 {active&&active.global_tokens?.studio_version!=='2'&&<p className="rounded-xl border bg-amber-50 p-4">{ar?'تصميمك الحالي محفوظ كما هو. يمكنك الاستمرار في تعديله، أو اختيار أحد التصاميم الجديدة أدناه.':'Your current design is preserved. Keep editing it, or choose a new design below.'}</p>}
 {!!saved.length&&<details className="rounded-xl border bg-white p-4"><summary className="cursor-pointer font-medium">{ar?'تصاميمي المحفوظة — الرجوع لتصميم سابق':'Saved designs — restore a previous design'}</summary><div className="mt-4 flex flex-wrap gap-3">{saved.map(s=><button key={s.id} disabled={!!busy} onClick={()=>restore(s.id)} className="rounded-lg border px-4 py-3 text-sm">{s.theme_versions?.themes?.name||s.theme_versions?.themes?.folder_name} · {s.theme_versions?.version}</button>)}</div></details>}
 <div className="grid gap-6 md:grid-cols-2 xl:grid-cols-3">{studioThemes.map(theme=>{const selected=active?.global_tokens?.studio_version==='2'&&active?.theme_versions?.themes?.folder_name===theme.id;return <article key={theme.id} className={`overflow-hidden rounded-2xl border bg-white ${selected?'ring-2 ring-teal-700':''}`}><Link href={`/theme-preview/${theme.id}`} target="_blank" aria-label={`${ar?'معاينة':'Preview'} ${ar?theme.name:theme.en}`}><img src={`/themes-studio/${theme.id}.jpg`} alt={ar?`لقطة حقيقية من ثيم ${theme.name}`:`Actual ${theme.en} theme screenshot`} className="aspect-[4/3] w-full object-cover object-top" loading="lazy"/></Link><div className="space-y-4 p-5"><div className="flex justify-between gap-3"><div><h2 className="text-xl font-bold">{ar?theme.name:theme.en}</h2><p className="text-sm text-muted-foreground">{ar?theme.tag:theme.tagEn}</p></div><div className="flex gap-1" aria-hidden="true">{[theme.primary,theme.soft,theme.background].map(c=><span key={c} className="h-5 w-5 rounded-full border" style={{background:c}}/>)}</div></div><div className="flex gap-2"><Link className="flex-1 rounded-lg border px-3 py-2 text-center" href={`/theme-preview/${theme.id}`} target="_blank">{ar?'معاينة مباشرة':'Live preview'}</Link><button disabled={!!busy||selected} onClick={()=>activate(theme.id)} className="flex-1 rounded-lg bg-teal-700 px-3 py-2 text-white disabled:opacity-60">{busy===theme.id?(ar?'جاري التطبيق…':'Applying…'):selected?(ar?'مفعّل':'Active'):(ar?'تطبيق':'Apply')}</button></div></div></article>})}</div></div>;
}
